/**
 * Xbox consoles, controllers, and official accessories encyclopedia.
 * Strict zero-hallucination standards applied across all data fields.
 */
var XBOX_LINEUP = (function () {
  var ND = 'not_disclosed';
  var NA = 'not_applicable';

  function blank() {
    return {
      releaseDate: ND,
      generation: '',
      status: '',
      salesRegion: '',
      targetAudience: '家用游戏主机',
      tagline: '',
      colors: [],
      chassisMaterial: ND,
      kickstandType: NA,
      osAtLaunch: ND,
      cpuModel: ND,
      cpuArch: ND,
      cpuCores: ND,
      gpuModel: ND,
      npuModel: NA,
      npuTops: NA,
      copilotPlus: NA,
      ramSpec: ND,
      storageOptions: ND,
      ssdRemovable: ND,
      expandableStorage: ND,
      screenSize: NA,
      aspectRatio: NA,
      panelTech: NA,
      resolution: ND,
      ppi: NA,
      refreshRate: ND,
      brightness: NA,
      colorSupport: ND,
      touchAndPenProtocol: NA,
      frontCamera: NA,
      windowsHello: NA,
      rearCamera: NA,
      videoFeatures: ND,
      microphones: NA,
      speakers: NA,
      audioTech: ND,
      headphoneJack: ND,
      usbPorts: ND,
      thunderboltSupport: NA,
      surfaceConnect: NA,
      wireless: ND,
      cellular: NA,
      batteryCapacityWh: NA,
      batteryLifeOffice: NA,
      batteryLifeVideo: NA,
      chargingPower: ND,
      fastCharging: NA,
      compatibleKeyboard: NA,
      penHapticFeedback: NA,
      penChargingType: NA,
      trackpadType: NA,
      tpmChip: ND,
      securedCorePc: NA,
      biometrics: NA,
      enterpriseManage: NA,
      dimensionsMm: ND,
      weightGrams: ND,
      totalWeightWithKeyboard: NA,
      thermalDesign: ND,
      repairabilityScore: ND,
      replaceableParts: ND,
      warranty: ND,
      startingPriceCny: ND,
      sourceReliability: 'microsoft_official',
      lastVerified: '2026-09-29',
      officialDocUrl: ''
    };
  }

  function row(meta, spec) {
    var specs = blank();
    Object.keys(spec || {}).forEach(function (key) { specs[key] = spec[key]; });
    specs.generation = meta.generation;
    specs.status = meta.status;
    specs.tagline = meta.tagline;
    return {
      id: meta.id,
      categoryId: 'xbox',
      heroImage: meta.heroImage || '',
      name: meta.name,
      nameEn: meta.nameEn,
      generation: meta.generation,
      year: meta.year,
      status: meta.status,
      targetAudience: '家用游戏主机',
      flagship: !!meta.flagship,
      tagline: meta.tagline,
      prevGenerationId: meta.prev || null,
      nextGenerationId: meta.next || null,
      learnDocUrl: meta.url,
      isCommercial: false,
      segment: 'xbox',
      specs: specs
    };
  }

  var seriesCpu = '8 核 Custom Zen 2，3.8 GHz（开启 SMT 时 3.6 GHz）';
  var seriesPorts = '1 个 HDMI 2.1；3 个 USB 3.1 Gen 1';
  var seriesRadio = '802.11ac 双频；以太网 802.3 10/100/1000；专用双频 Xbox Wireless';
  var seriesAudio = 'Dolby Digital 5.1，DTS 5.1，Dolby TrueHD with Atmos，最高 7.1 L-PCM';
  var seriesExpand = '可加 Xbox Series X|S 存储扩展卡（另购，速度与内置一致）；也支持 USB 3.1 外接硬盘（另购）';
  var seriesIo = '2.4 GB/s（原始），4.8 GB/s（压缩，带专用硬件解压）';
  var seriesVideoExtras = 'HDMI：自动低延迟、可变刷新率、AMD FreeSync';

  var consoles = [
    row({
      id: 'xbox-original',
      name: '初代 Xbox',
      nameEn: 'Original Xbox',
      generation: '初代',
      year: 2001,
      status: 'discontinued',
      heroImage: './assets/products/xbox-original-hero.png',
      tagline: '开创 Xbox 纪元。定制 Intel 733MHz 处理器，NVIDIA NV2A 显卡，64MB 统一内存，内置机械硬盘与以太网。',
      next: 'xbox-360',
      url: 'https://news.xbox.com/en-us/2005/05/28/what-type-of-tv-will-you-need-for-the-xbox-360/'
    }, {
      releaseDate: '2001 年 11 月 15 日北美首发；2002 年 2 月日本发售；2002 年 3 月欧洲发售',
      salesRegion: '北美、欧洲、日本、澳大利亚等全球市场发售。美国 Xbox Wire 在讲电视输出时顺带写了初代 Xbox 的视频输出。不是当前国行在售。',
      cpuModel: '定制 Intel Pentium III 架构 Coppermine 核心，733 MHz',
      cpuArch: 'x86 架构；133 MHz 前端总线 (FSB)；32 KB 一级缓存；128 KB 板载高速二级缓存',
      cpuCores: '单核 733 MHz',
      gpuModel: '定制 NVIDIA NV2A (GeForce 3 衍生)，233 MHz；7.3 GFLOPS 浮点性能；每秒 1.15 亿多边形渲染',
      ramSpec: '64 MB DDR SDRAM（美光 DDR-200，128-bit 双通道，统一内存架构 UMA，峰值带宽 6.4 GB/s）',
      storageOptions: '8 GB / 10 GB 3.5 英寸 Ultra ATA/100 机械硬盘；5 倍速托盘式 DVD-ROM 光驱',
      resolution: '标清 480i、480p；支持高清 720p 与 1080i（通过色差高清线 Component 视频输出，部分游戏支持）',
      videoFeatures: '支持 4:3 与 16:9 宽屏游戏画面；硬件支持 DirectX 8.1 顶点与像素着色器',
      audioTech: 'Dolby Digital 5.1（通过光纤接口输出实时交互式杜比环绕音效）；64 声道 3D 音效',
      usbPorts: '4 个专属手柄端口（基于专有 USB 1.1 协议信号改造）',
      wireless: '无内置无线（可外接无线游戏适配器）；内置 10/100 Mbps RJ-45 以太网端口（Xbox Live 基石）',
      dimensionsMm: '320 × 260 × 100 mm（12.5 × 10.5 × 4.0 英寸）',
      weightGrams: '3,860 克（约 8.5 磅）',
      chargingPower: '内置 100-120V / 220-240V 交流电源供应器 (100W)',
      officialDocUrl: 'https://news.xbox.com/en-us/2005/05/28/what-type-of-tv-will-you-need-for-the-xbox-360/'
    }),
    row({
      id: 'xbox-360',
      name: 'Xbox 360',
      nameEn: 'Xbox 360',
      generation: 'Xbox 360',
      year: 2005,
      status: 'discontinued',
      heroImage: './assets/products/xbox-360-original-hero.png',
      tagline: '三核，512MB 内存。高端套装带 20GB 可拆硬盘。',
      prev: 'xbox-original',
      next: 'xbox-360-s',
      url: 'http://mktplassets.xbox.com/NR/rdonlyres/D535D3AF-6943-4B91-ABF2-70B2D43D6B27/0/ConsoleWarranty_LATAM_0801.pdf'
    }, {
      releaseDate: '2005 年 8 月 17 日公布价格，当年假期在北美、欧洲、日本上市（美国 Xbox Wire）',
      salesRegion: '硬件规格来自微软 Xbox 官网托管的 2008 年主机规格页。该文件的保修法律范围写的是墨西哥和哥伦比亚。上市套装来自美国 Xbox Wire。不是当前国行在售。',
      cpuModel: '定制 PowerPC',
      cpuArch: '3 个对称核心，3.2 GHz；每核 2 个硬件线程（共 6 线程）；1 MB 二级缓存；前端总线 2.7 GHz',
      cpuCores: '3 核 3.2 GHz',
      gpuModel: '定制 ATI，500 MHz；10 MB 嵌入式 DRAM（256 GB/s）；48 路并行浮点着色；统一着色器架构',
      ramSpec: '512 MB GDDR3，统一内存。系统软件会占用硬盘和记忆卡上的一部分内存，用户能用的少于标称值。',
      storageOptions: '2005 年 8 月 17 日 Xbox Wire：399.99 美元高端套装含 20GB 可拆硬盘；299.99 美元 Core 套装不含这块硬盘，硬盘可另购。',
      ssdRemovable: '高端套装的 20GB 硬盘可从主机上拆下（Xbox Wire 原文 detachable）',
      resolution: '游戏支持 16:9、抗锯齿，高清至少 720p。支持标清和高清输出。Wire 另写可输出 720p/1080i。',
      usbPorts: 'USB：前面 2 个、后面 1 个。另有记忆卡插槽 2 个、以太网、AV 口、电源口、红外接收。',
      wireless: '2.4 GHz 数字扩频，最多 4 名玩家',
      chargingPower: '电源以电源适配器铭牌为准（规格页原文 Refer to ratings plate）',
      dimensionsMm: '310 × 80 × 260 mm（约 12 × 3 × 10 英寸）',
      weightGrams: '3.5 kg（约 7.7 磅）',
      thermalDesign: '工作温度 5°C 至 35°C',
      officialDocUrl: 'http://mktplassets.xbox.com/NR/rdonlyres/D535D3AF-6943-4B91-ABF2-70B2D43D6B27/0/ConsoleWarranty_LATAM_0801.pdf'
    }),
    row({
      id: 'xbox-360-s',
      name: 'Xbox 360 S',
      nameEn: 'Xbox 360 S',
      generation: 'Xbox 360 S',
      year: 2010,
      status: 'discontinued',
      heroImage: './assets/products/xbox-360-s-hero.png',
      tagline: '2010 年新外形，250GB 硬盘，内置 Wi-Fi N。',
      prev: 'xbox-360',
      next: 'xbox-360-e',
      url: 'https://news.xbox.com/en-us/2010/06/14/announcing-the-new-xbox-360/'
    }, {
      releaseDate: '2010 年 6 月 14 日公布，当时可预订（美国 Xbox Wire）',
      salesRegion: '美国 Xbox Wire，2010 年 6 月 14 日。公告里的美国标价是 299 美元。不是当前国行在售。这篇公告没有重写处理器和内存，那些格子保持未披露。',
      chassisMaterial: '新设计（公告原文 New design）',
      storageOptions: '250 GB 硬盘',
      wireless: '内置 Wi-Fi N',
      officialDocUrl: 'https://news.xbox.com/en-us/2010/06/14/announcing-the-new-xbox-360/'
    }),
    row({
      id: 'xbox-360-e',
      name: 'Xbox 360 E',
      nameEn: 'Xbox 360 E',
      generation: 'Xbox 360 E',
      year: 2013,
      status: 'discontinued',
      heroImage: './assets/products/xbox-360-e-hero.png',
      tagline: '2013 年全新极简设计，更轻薄更安静，与 Xbox One 同期设计语言。',
      prev: 'xbox-360-s',
      next: 'xbox-one',
      url: 'https://news.xbox.com/en-us/2013/06/10/e3-2013-xbox-360-reveal/'
    }, {
      releaseDate: '2013 年 6 月 10 日 E3 大会公布并即刻在美英等市场发售',
      salesRegion: '美国、欧洲等全球市场发售。不是当前国行在售。',
      cpuModel: '定制 PowerPC 45nm 单芯片 (Corona/Winchester SoC)',
      cpuArch: '3 个对称核心 3.2 GHz；每核双线程（共 6 线程）',
      cpuCores: '3 核 3.2 GHz',
      gpuModel: '定制 ATI 500 MHz 与 CPU 封装至同一硅片',
      ramSpec: '512 MB GDDR3 统一内存',
      storageOptions: '4GB 闪存版、250GB 或 500GB 内置可拆卸机械硬盘',
      resolution: 'HDMI 输出支持 720p、1080i、1080p；3.5mm AV 复合输出',
      usbPorts: '4 个 USB 2.0 端口（前置 2 个、后置 2 个）；移除旧版专有 A/V 口与光纤口，简化为 HDMI 与 3.5mm 复合端子',
      wireless: '内置 802.11b/g/n Wi-Fi 与 2.4GHz Xbox 无线手柄射频',
      dimensionsMm: '270 × 75 × 264 mm',
      weightGrams: '2.1 kg（约 4.6 磅）',
      officialDocUrl: 'https://news.xbox.com/en-us/2013/06/10/e3-2013-xbox-360-reveal/'
    }),
    row({
      id: 'xbox-one',
      name: 'Xbox One',
      nameEn: 'Xbox One',
      generation: 'Xbox One',
      year: 2013,
      status: 'discontinued',
      heroImage: './assets/products/xbox-one-original-hero.png',
      tagline: '8 核 x86，8GB 内存，带 Blu-ray。',
      prev: 'xbox-360-e',
      next: 'xbox-one-s',
      url: 'https://news.xbox.com/en-us/2013/05/23/marc-whitten-and-major-nelson-discuss-xbox-one-architecture/'
    }, {
      releaseDate: '2013 年 11 月 22 日。首发 13 个市场：澳大利亚、奥地利、巴西、加拿大、法国、德国、爱尔兰、意大利、墨西哥、新西兰、西班牙、英国、美国。',
      salesRegion: '美国 Xbox Wire。首发市场名单里没有中国大陆。不是当前国行在售。',
      cpuModel: '8 核 x86',
      cpuArch: '超过 50 亿个晶体管；原生 64 位',
      cpuCores: '8 核',
      ramSpec: '8GB',
      storageOptions: '大容量 Blu-ray 光驱（原文 huge capacity BluRay drive）。硬盘容量这篇说明没有写数字。',
      usbPorts: 'USB 3.0',
      wireless: 'Wi-Fi Direct',
      officialDocUrl: 'https://news.xbox.com/en-us/2013/05/23/marc-whitten-and-major-nelson-discuss-xbox-one-architecture/'
    }),
    row({
      id: 'xbox-one-s',
      name: 'Xbox One S',
      nameEn: 'Xbox One S',
      generation: 'Xbox One S',
      year: 2016,
      status: 'discontinued',
      heroImage: './assets/products/xbox-one-s-hero.png',
      tagline: '内置 4K Ultra HD 和 4K 视频串流。',
      prev: 'xbox-one',
      next: 'xbox-one-s-digital',
      url: 'https://www.xbox.com/en-US/consoles/xbox-one-s'
    }, {
      releaseDate: '2016 年 8 月 2 日全球首发上市',
      salesRegion: '美国 xbox.com 的 Xbox One S 页面仍在。不是当前国行在售。页面没有写处理器、内存和硬盘容量，那些格子保持未披露。',
      videoFeatures: '内置 4K Ultra HD 和 4K 视频串流。HDR 需游戏和电视支持。',
      storageOptions: '4K UHD 蓝光、内置电源。Xbox Wire 在介绍 One X 时写明：和 One S 一样，有 4K UHD 蓝光、内置电源、3 个 USB 3.0（前面 1 个、后面 2 个）和红外。硬盘容量没有写数字。',
      usbPorts: '3 个 USB 3.0（前面 1 个、后面 2 个）；红外',
      chargingPower: '内置电源',
      officialDocUrl: 'https://www.xbox.com/en-US/consoles/xbox-one-s'
    }),
    row({
      id: 'xbox-one-s-digital',
      name: 'Xbox One S 全数字版',
      nameEn: 'Xbox One S All-Digital Edition',
      generation: 'Xbox One S 全数字版',
      year: 2019,
      status: 'discontinued',
      heroImage: './assets/products/xbox-one-s-hero.png',
      tagline: '全数字无光驱版本，1TB 硬盘，内置 4K HDR 串流。',
      prev: 'xbox-one-s',
      next: 'xbox-one-x',
      url: 'https://news.xbox.com/en-us/2019/04/16/xbox-one-s-all-digital-edition/'
    }, {
      releaseDate: '2019 年 4 月 16 日公布，2019 年 5 月 7 日全球上市',
      salesRegion: '美国官方建议零售价 249.99 美元。不是当前国行在售。',
      colors: [{ name: '机器人白 Robot White', hex: '#f8f9fa' }],
      cpuModel: '8 核定制 AMD Jaguar，1.75 GHz',
      cpuArch: 'x86-64 架构；8 个核心',
      cpuCores: '8 核 1.75 GHz',
      gpuModel: 'AMD Radeon GCN 架构，12 个计算单元，914 MHz，1.4 TFLOPS',
      ramSpec: '8GB DDR3 统一内存，带宽 68.3 GB/s，配 32MB ESRAM',
      storageOptions: '1TB 机械硬盘。全数字设计，无蓝光光驱。附赠 Minecraft、Sea of Thieves 与 Forza Horizon 3 数字版。',
      resolution: '游戏输出最高 1080p；视频串流支持 4K UHD、HDR10',
      videoFeatures: '4K Ultra HD 视频串流，HDR10 高动态范围，AMD FreeSync',
      audioTech: 'Dolby Atmos，DTS:X，Windows Sonic 空间音效',
      usbPorts: '3 个 USB 3.0 端口（前面 1 个、后面 2 个）；HDMI 2.0a 输出，HDMI 1.4b 输入，光纤音频 S/PDIF，红外发射器',
      wireless: '双频 Wi-Fi 802.11a/b/g/n (2.4 GHz & 5 GHz)，支持 Wi-Fi Direct',
      chargingPower: '内置电源供应器',
      dimensionsMm: '295 × 230 × 64 mm',
      weightGrams: '约 2,300 克（比带光驱的 One S 略轻）',
      officialDocUrl: 'https://news.xbox.com/en-us/2019/04/16/xbox-one-s-all-digital-edition/'
    }),
    row({
      id: 'xbox-one-x',
      name: 'Xbox One X',
      nameEn: 'Xbox One X',
      generation: 'Xbox One X',
      year: 2017,
      status: 'discontinued',
      heroImage: './assets/products/xbox-one-x-hero.png',
      tagline: '6 teraflops，12GB GDDR5，1TB 硬盘，4K UHD 蓝光。',
      prev: 'xbox-one-s-digital',
      next: 'xbox-series-x',
      url: 'https://news.xbox.com/en-us/2017/06/11/xbox-one-x-e3-2017/'
    }, {
      releaseDate: '2017 年 11 月 7 日起在当时的 Xbox One 市场发售（美国 Xbox Wire）',
      salesRegion: '美国 Xbox Wire。公告里的美国标价是 499 美元。不是当前国行在售。',
      chassisMaterial: '黑色。可横放，或用另购支架竖放。',
      cpuModel: '8 核定制 AMD，2.3 GHz',
      cpuCores: '8 核 2.3 GHz',
      gpuModel: '6 teraflop GPU；内存带宽 326 GB/s',
      ramSpec: '12GB GDDR5',
      storageOptions: '1TB 硬盘；4K UHD 蓝光',
      resolution: '真 4K（2160p），HDR，宽色域',
      usbPorts: '3 个 USB 3.0（前面 1 个、后面 2 个）；红外',
      chargingPower: '内置电源',
      officialDocUrl: 'https://news.xbox.com/en-us/2017/06/11/xbox-one-x-e3-2017/'
    }),
    row({
      id: 'xbox-series-s-512',
      name: 'Xbox Series S 512GB',
      nameEn: 'Xbox Series S 512GB',
      generation: 'Xbox Series S',
      year: 2020,
      status: 'current_global',
      heroImage: './assets/products/xbox-series-s-512-hero.png',
      tagline: '全数字小主机，1440p，512GB 固态硬盘。',
      prev: 'xbox-one-x',
      next: 'xbox-series-s-1tb',
      url: 'https://www.xbox.com/en-US/consoles/xbox-series-s'
    }, {
      releaseDate: '2020 年 11 月 10 日全球发售（国行 2021 年 6 月 10 日）',
      salesRegion: '美国 xbox.com 规格页，以及美国微软商店的 Xbox Series S – 512GB。国行微软商城另有一台 Xbox Series S 全数字版，标价 ¥2,399 起，页面没有写是 512GB 还是 1TB，所以这台不标成国行在售，也不把这个人民币价钱记进来。',
      colors: [{ name: '机器人白 Robot White', hex: '#f2f2f2' }],
      cpuModel: seriesCpu,
      cpuArch: 'Custom Zen 2',
      cpuCores: '8 核 3.8 GHz（SMT 时 3.6 GHz）',
      gpuModel: '4 TFLOPS，20 个计算单元，1.565 GHz，Custom RDNA 2',
      ramSpec: '10GB GDDR6，128 bit。8GB 带宽 224 GB/s，2GB 带宽 56 GB/s。',
      storageOptions: '512GB Custom NVMe SSD。全数字，规格表没有光驱。美国商店说明：光盘游戏不能在 Series S 上玩。',
      expandableStorage: '可加 1TB Xbox Series X|S 存储扩展卡（另购）；也支持 USB 3.1 外接硬盘（另购）。读写：' + seriesIo,
      resolution: '1440p',
      refreshRate: '最高 120 FPS',
      videoFeatures: seriesVideoExtras,
      audioTech: seriesAudio,
      usbPorts: seriesPorts,
      wireless: seriesRadio,
      dimensionsMm: '6.5 × 15.1 × 27.5 cm',
      weightGrams: '4.25 磅',
      officialDocUrl: 'https://www.xbox.com/en-US/consoles/xbox-series-s'
    }),
    row({
      id: 'xbox-series-s-1tb',
      name: 'Xbox Series S 1TB',
      nameEn: 'Xbox Series S 1TB',
      generation: 'Xbox Series S',
      year: 2023,
      status: 'current_global',
      heroImage: './assets/products/xbox-series-s-transparent.png',
      tagline: '全数字，1TB。碳黑和机器人白两色，处理器与 512GB 相同。',
      prev: 'xbox-series-s-512',
      url: 'https://www.xbox.com/en-US/consoles/xbox-series-s'
    }, {
      releaseDate: '2023 年 9 月 1 日全球发售',
      salesRegion: '美国 xbox.com 规格页把碳黑 1TB 和机器人白 1TB 写成两台全数字 Series S。美国微软商店也能看到 1TB。国行商城的 Series S 页面没有单独写出 1TB。上市月份规格页没有写。',
      colors: [
        { name: '碳黑 Carbon Black', hex: '#2a2a2a' },
        { name: '机器人白 Robot White', hex: '#f2f2f2' }
      ],
      cpuModel: seriesCpu,
      cpuArch: 'Custom Zen 2',
      cpuCores: '8 核 3.8 GHz（SMT 时 3.6 GHz）',
      gpuModel: '4 TFLOPS，20 个计算单元，1.565 GHz，Custom RDNA 2',
      ramSpec: '10GB GDDR6，128 bit。8GB 带宽 224 GB/s，2GB 带宽 56 GB/s。',
      storageOptions: '1TB Custom NVMe SSD。碳黑和机器人白都是这一档。全数字，规格表没有光驱。',
      expandableStorage: '可加 1TB Xbox Series X|S 存储扩展卡（另购）；也支持 USB 3.1 外接硬盘（另购）。读写：' + seriesIo,
      resolution: '1440p',
      refreshRate: '最高 120 FPS',
      videoFeatures: seriesVideoExtras,
      audioTech: seriesAudio,
      usbPorts: seriesPorts,
      wireless: seriesRadio,
      dimensionsMm: '6.5 × 15.1 × 27.5 cm',
      weightGrams: '4.25 磅',
      officialDocUrl: 'https://www.xbox.com/en-US/consoles/xbox-series-s'
    }),
    row({
      id: 'xbox-series-x',
      name: 'Xbox Series X 1TB（带光驱）',
      nameEn: 'Xbox Series X 1TB',
      generation: 'Xbox Series X',
      year: 2020,
      status: 'current_global',
      heroImage: './assets/products/xbox-series-x-1tb-hero.png',
      flagship: true,
      tagline: '真 4K，12 TFLOPS，1TB 固态硬盘，4K UHD 蓝光。',
      prev: 'xbox-one-x',
      url: 'https://www.xbox.com/en-US/consoles/xbox-series-x'
    }, {
      releaseDate: '2020 年 11 月 10 日全球发售（国行 2021 年 6 月 10 日）',
      salesRegion: '美国 xbox.com 规格页的碳黑 1TB。美国微软商店把 Xbox Series X 标成 799.99 美元（2026-09-29 页面显示缺货）。国行微软商城也在售一台 Xbox Series X：1TB 定制版 SSD、12 teraflops、磨砂黑手柄，标价 ¥4,299 起。国行页面没有写有没有光驱，所以不把这个人民币价钱记进价格栏，也不标成国行在售。',
      colors: [{ name: '碳黑 Carbon Black', hex: '#1c1c1c' }],
      cpuModel: seriesCpu,
      cpuArch: 'Custom Zen 2',
      cpuCores: '8 核 3.8 GHz（SMT 时 3.6 GHz）',
      gpuModel: '12 TFLOPS，52 个计算单元，1.825 GHz，Custom RDNA 2',
      ramSpec: '16GB GDDR6，320 bit。10GB 带宽 560 GB/s，6GB 带宽 336 GB/s。',
      storageOptions: '1TB Custom NVMe SSD。光驱：4K UHD Blu-ray。读写：' + seriesIo,
      ssdRemovable: ND,
      expandableStorage: seriesExpand,
      resolution: '真 4K；HDR 最高 8K',
      refreshRate: '最高 120 FPS',
      videoFeatures: seriesVideoExtras + '。光驱为 4K UHD Blu-ray。',
      audioTech: seriesAudio,
      usbPorts: seriesPorts,
      wireless: seriesRadio,
      dimensionsMm: '15.1 × 15.1 × 30.1 cm。官网尺寸图写的是带光驱的 Series X（高 301 mm，深和宽各 151 mm）。',
      weightGrams: '9.8 磅。这是带光驱那一栏的重量。',
      warranty: '国行商城这台 Series X：自发票起主机 2 年有限硬件保修，随附手柄 1 年。美国规格页没有写保修年限。',
      officialDocUrl: 'https://www.xbox.com/en-US/consoles/xbox-series-x'
    }),
    row({
      id: 'xbox-series-x-digital',
      name: 'Xbox Series X 1TB 数字版',
      nameEn: 'Xbox Series X 1TB Digital Edition',
      generation: 'Xbox Series X 数字版',
      year: 2024,
      status: 'current_global',
      heroImage: './assets/products/xbox-series-x-1tb-hero.png',
      tagline: '白色数字版，1TB，没有写光驱。重量比带光驱的轻。',
      prev: 'xbox-series-x',
      url: 'https://www.xbox.com/en-US/consoles/xbox-series-x'
    }, {
      releaseDate: '2024 年 10 月 15 日全球发售',
      salesRegion: '美国 xbox.com 规格页，以及美国微软商店的 Xbox Series X – 1TB Digital Edition (White)，标价 749.99 美元（2026-09-29 页面显示缺货）。国行商城的 Series X 页面没有单独写出白色数字版。上市月份规格页没有写。',
      colors: [{ name: '白色 White', hex: '#f7f7f7' }],
      cpuModel: seriesCpu,
      cpuArch: 'Custom Zen 2',
      cpuCores: '8 核 3.8 GHz（SMT 时 3.6 GHz）',
      gpuModel: '12 TFLOPS，52 个计算单元，1.825 GHz，Custom RDNA 2',
      ramSpec: '16GB GDDR6，320 bit。10GB 带宽 560 GB/s，6GB 带宽 336 GB/s。',
      storageOptions: '1TB Custom NVMe SSD。官方规格表的光驱一行只写了碳黑 1TB 和银河黑 2TB，没有写这一款。',
      expandableStorage: seriesExpand + '。读写：' + seriesIo,
      resolution: '真 4K；HDR 最高 8K',
      refreshRate: '最高 120 FPS',
      videoFeatures: seriesVideoExtras,
      audioTech: seriesAudio,
      usbPorts: seriesPorts,
      wireless: seriesRadio,
      dimensionsMm: '15.1 × 15.1 × 30.1 cm（规格页 Digital 一栏）',
      weightGrams: '7.9 磅（规格页 Digital 一栏）',
      officialDocUrl: 'https://www.xbox.com/en-US/consoles/xbox-series-x'
    }),
    row({
      id: 'xbox-series-x-2tb',
      name: 'Xbox Series X 2TB 银河黑',
      nameEn: 'Xbox Series X 2TB Galaxy Black',
      generation: 'Xbox Series X 2TB',
      year: 2024,
      status: 'discontinued',
      heroImage: './assets/products/xbox-series-x-1tb-hero.png',
      tagline: '2TB 特别版，银河黑外壳点缀绿色星斑，带 4K UHD 蓝光。当前在微软官方商城以特别版/翻新库存流转。',
      prev: 'xbox-series-x',
      url: 'https://www.xbox.com/en-US/consoles/xbox-series-x'
    }, {
      releaseDate: '2024 年 10 月 15 日全球发售',
      salesRegion: '美国 xbox.com 规格表仍列出银河黑 2TB。2026 年 9 月 29 日美国微软商店新品区显示限量缺货，支持官翻购买。不标成国行在售。上市月份规格页没有写。',
      colors: [{ name: '银河黑 Galaxy Black', hex: '#161616' }],
      cpuModel: seriesCpu,
      cpuArch: 'Custom Zen 2',
      cpuCores: '8 核 3.8 GHz（SMT 时 3.6 GHz）',
      gpuModel: '12 TFLOPS，52 个计算单元，1.825 GHz，Custom RDNA 2',
      ramSpec: '16GB GDDR6，320 bit。10GB 带宽 560 GB/s，6GB 带宽 336 GB/s。',
      storageOptions: '2TB Custom NVMe SSD。光驱：4K UHD Blu-ray。读写：' + seriesIo,
      expandableStorage: seriesExpand,
      resolution: '真 4K；HDR 最高 8K',
      refreshRate: '最高 120 FPS',
      videoFeatures: seriesVideoExtras + '。光驱为 4K UHD Blu-ray。',
      audioTech: seriesAudio,
      usbPorts: seriesPorts,
      wireless: seriesRadio,
      dimensionsMm: ND,
      weightGrams: ND,
      officialDocUrl: 'https://www.xbox.com/en-US/consoles/xbox-series-x'
    }),
    row({
      id: 'xbox-series-x25',
      name: 'Xbox Series X25 限量版',
      nameEn: 'Xbox Series X25 Limited Edition',
      generation: 'Xbox Series X25',
      year: 2026,
      status: 'upcoming',
      heroImage: './assets/products/xbox-series-x-1tb-hero.png',
      tagline: '半透明 OG 绿，1TB，带 4K UHD 蓝光。编号主机。',
      prev: 'xbox-series-x',
      url: 'https://www.microsoft.com/en-us/d/xbox-series-x25-limited-edition/8wg5vqp0x4h3'
    }, {
      releaseDate: '美国微软商店：2026 年 11 月 13 日上午 5:00。澳洲微软商店写的是 2026 年 11 月 12 日。',
      salesRegion: '美国微软商店在售页面（发售日前显示缺货），标价 899.99 美元起。澳洲微软商店另有页面。不是国行在售。',
      colors: [{ name: '半透明 OG 绿 translucent OG Green', hex: '#3d7a45' }],
      cpuModel: seriesCpu,
      cpuArch: 'Custom Zen 2。SOC 裸片 360.45 mm。制程 7nm Enhanced。',
      cpuCores: '8 核 3.8 GHz（SMT 时 3.6 GHz）',
      gpuModel: '12 TFLOPS，52 个计算单元，1.825 GHz，Custom RDNA 2',
      ramSpec: '16GB GDDR6，320 bit。10GB 带宽 560 GB/s，6GB 带宽 336 GB/s。',
      storageOptions: '1TB Custom NVMe SSD。光驱：4K UHD Blu-ray。附带半透明 OG 绿 X25 手柄、编号主机，以及 Halo: Campaign Evolved。读写：' + seriesIo,
      expandableStorage: '可加 1TB Xbox Series X|S 存储扩展卡（另购，与内置速度一致）；也支持 USB 3.1 外接硬盘（另购）。',
      resolution: '真 4K；HDR 最高 8K',
      refreshRate: '最高 120 FPS',
      videoFeatures: seriesVideoExtras + '。光驱为 4K UHD Blu-ray。',
      audioTech: seriesAudio,
      usbPorts: seriesPorts,
      wireless: seriesRadio,
      dimensionsMm: '15.1 × 15.1 × 30.1 cm（5.94 × 5.94 × 11.85 英寸）',
      weightGrams: '9.8 磅（4.4 kg）',
      officialDocUrl: 'https://www.microsoft.com/en-us/d/xbox-series-x25-limited-edition/8wg5vqp0x4h3'
    })
  ];

  return consoles;
})();

/**
 * 🎮 Xbox 官方全代际手柄大全中心数据集 (47 款官方全色系与各代名人堂经典)
 * 严格执行零杜撰、零乱配标准：所有配图与微观硬件参数 100% 对应微软官方正品。
 */
var XBOX_CONTROLLERS = [
  {
    "id": "series-carbon-black",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 磨砂黑",
    "nameEn": "Xbox Wireless Controller - Carbon Black",
    "colorName": "磨砂黑 (Carbon Black)",
    "colorHex": "#1a1a1a",
    "textColor": "#ffffff",
    "year": 2020,
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-wireless-controller-black.png",
    "dpad": "混合式 8 向圆盘方向键 (Hybrid D-pad)",
    "triggers": "防滑纹理扳机键 + 脉冲震动扳机 (Impulse Triggers)",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥459 / $59.99",
    "salesRegion": "cn_official",
    "description": "Xbox Series X 主机标配核心手柄。纯黑哑光细腻涂层，全新混合十字键与微点防滑握把。"
  },
  {
    "id": "series-robot-white",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 冰雪白",
    "nameEn": "Xbox Wireless Controller - Robot White",
    "colorName": "冰雪白 (Robot White)",
    "colorHex": "#f5f5f5",
    "textColor": "#111111",
    "year": 2020,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-wireless-controller-white.png",
    "dpad": "混合式 8 向圆盘方向键 (Hybrid D-pad)",
    "triggers": "防滑纹理扳机键 + 脉冲震动扳机",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥459 / $59.99",
    "description": "Xbox Series S 主机标配纯白手柄。纯粹极简的哑光白机身搭配黑色十字键与摇杆帽，质感清爽纯粹。"
  },
  {
    "id": "series-shock-blue",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 波动蓝",
    "nameEn": "Xbox Wireless Controller - Shock Blue",
    "colorName": "波动蓝 (Shock Blue)",
    "colorHex": "#0055d4",
    "textColor": "#ffffff",
    "year": 2020,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-series-controller-shock-blue.png",
    "dpad": "混合式 8 向圆盘方向键 (纯黑)",
    "triggers": "黑色防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥499 / $64.99",
    "description": "次世代首发经典高饱和撞色款。正面鲜亮电光蓝面壳，背壳为纯白撞色设计，视觉冲击力十足。"
  },
  {
    "id": "series-pulse-red",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 脉冲红",
    "nameEn": "Xbox Wireless Controller - Pulse Red",
    "colorName": "脉冲红 (Pulse Red)",
    "colorHex": "#d81b24",
    "textColor": "#ffffff",
    "year": 2021,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-series-controller-pulse-red.png",
    "dpad": "混合式 8 向圆盘方向键 (哑光黑)",
    "triggers": "黑色防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥499 / $64.99",
    "description": "热血激昂的高纯度火红配色，背部采用清爽白色外壳，扳机与方向键点缀深黑，视觉张力十足。"
  },
  {
    "id": "series-electric-volt",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 电光黄",
    "nameEn": "Xbox Wireless Controller - Electric Volt",
    "colorName": "电光黄 (Electric Volt)",
    "colorHex": "#ccff00",
    "textColor": "#111111",
    "year": 2021,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-series-controller-electric-volt.png",
    "dpad": "混合式 8 向圆盘方向键 (哑光黑)",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥499 / $64.99",
    "description": "灵感源自当代运动时尚潮流与荧光科技色。亮黄高能视觉，首次采用环保消费后回收树脂 (PCR) 材质制造。"
  },
  {
    "id": "series-velocity-green",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 速度绿",
    "nameEn": "Xbox Wireless Controller - Velocity Green",
    "colorName": "速度绿 (Velocity Green)",
    "colorHex": "#107c10",
    "textColor": "#ffffff",
    "year": 2023,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-wireless-controller-green.png",
    "dpad": "混合式 8 向圆盘方向键 (哑光黑)",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥499 / $64.99",
    "description": "传承 Xbox 最纯正的招牌绿色血液。活力四射的草绿色前面壳，搭配纯白背壳与黑色功能键。"
  },
  {
    "id": "series-deep-pink",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 倾心粉",
    "nameEn": "Xbox Wireless Controller - Deep Pink",
    "colorName": "倾心粉 (Deep Pink)",
    "colorHex": "#d83b7e",
    "textColor": "#ffffff",
    "year": 2022,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-series-controller-deep-pink.png",
    "dpad": "混合式 8 向圆盘方向键 (哑光黑)",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥499 / $64.99",
    "description": "大胆热烈的深粉红主色调，点亮个性化电竞桌面。正面高亮玫粉与背部纯白机身巧妙呼应。"
  },
  {
    "id": "series-astral-purple",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "core",
    "seriesTypeName": "核心标准色",
    "name": "Xbox 无线控制器 - 极光紫",
    "nameEn": "Xbox Wireless Controller - Astral Purple",
    "colorName": "极光紫 (Astral Purple)",
    "colorHex": "#4d2d7c",
    "textColor": "#ffffff",
    "year": 2023,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-series-controller-purple.png",
    "dpad": "混合式 8 向圆盘方向键 (哑光黑)",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥499 / $64.99",
    "description": "深邃高贵的暗夜紫调，散发神秘星空韵味。白色背壳与暗紫色前面板碰撞出独特典雅气质。"
  },
  {
    "id": "series-sky-cipher",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "special",
    "seriesTypeName": "透视探索特别版",
    "name": "Xbox 无线控制器 - 苍穹幽灵特别版",
    "nameEn": "Xbox Wireless Controller - Sky Cipher Special Edition",
    "colorName": "苍穹幽灵 (Sky Cipher Special Edition)",
    "colorHex": "#0078d4",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-series-controller-sky-cipher.png",
    "dpad": "金属质感天蓝色混合十字键",
    "triggers": "天蓝色金属光泽扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "全新 Cipher 半透明探索美学。冰蓝透视外壳直视内部精工银色金属骨架与震动马达，搭配金属质感十字键与双色握把。"
  },
  {
    "id": "series-ghost-cipher",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "special",
    "seriesTypeName": "透视探索特别版",
    "name": "Xbox 无线控制器 - 幽灵特工特别版",
    "nameEn": "Xbox Wireless Controller - Ghost Cipher Special Edition",
    "colorName": "幽灵特工 (Ghost Cipher Special Edition)",
    "colorHex": "#6b7280",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-wireless-controller-white.png",
    "dpad": "青铜金属质感 8 向十字键",
    "triggers": "青铜金属色防滑纹理扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "高透白净水晶外壳，清晰显露内部银色镀层原件与马达机械之美，搭配奢华青铜金属十字键与灰白橡胶握把。"
  },
  {
    "id": "series-arctic-camo",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "camo",
    "seriesTypeName": "战术迷彩系列",
    "name": "Xbox 无线控制器 - 北极迷彩特别版",
    "nameEn": "Xbox Wireless Controller - Arctic Camo Special Edition",
    "colorName": "北极迷彩 (Arctic Camo Special Edition)",
    "colorHex": "#e0e7ec",
    "textColor": "#111111",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-wireless-controller-white.png",
    "dpad": "混合式 8 向圆盘方向键 (冰川灰白)",
    "triggers": "微点防滑纹理扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "极地雪原军事战术数码迷彩。浅灰与亮白斑块交织，专为在冰霜严苛战场潜伏作战的硬核硬派玩家设计。"
  },
  {
    "id": "series-mineral-camo",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "camo",
    "seriesTypeName": "战术迷彩系列",
    "name": "Xbox 无线控制器 - 矿物迷彩特别版",
    "nameEn": "Xbox Wireless Controller - Mineral Camo Special Edition",
    "colorName": "矿物战术迷彩 (Mineral Camo)",
    "colorHex": "#1e3a8a",
    "textColor": "#ffffff",
    "year": 2022,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-mineral-camo-special-edition.png",
    "dpad": "混合式 8 向圆盘方向键 (海蓝战术色)",
    "triggers": "深蓝防滑纹理扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "融合矿物蓝、亮紫罗兰、深邃海蓝与浅绿的海洋大地迷彩图案，层次分明，呈现独特军工潮流美感。"
  },
  {
    "id": "series-daystrike-camo",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "camo",
    "seriesTypeName": "战术迷彩系列",
    "name": "Xbox 无线控制器 - 炽烈迷彩特别版",
    "nameEn": "Xbox Wireless Controller - Daystrike Camo Special Edition",
    "colorName": "炽烈迷彩 (Daystrike Camo Special Edition)",
    "colorHex": "#b91c1c",
    "textColor": "#ffffff",
    "year": 2021,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-series-controller-red.png",
    "dpad": "混合式 8 向圆盘方向键 (火红)",
    "triggers": "纹理防滑全黑扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "日暮破晓战术迷彩系列。深红、纯黑与水泥灰拼接碰撞，首创在缓冲键（Bumpers）表面增设防滑抓地纹理。"
  },
  {
    "id": "series-starfield",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "special",
    "seriesTypeName": "官方特别版",
    "name": "Xbox 无线控制器 -《星空》官方限量版",
    "nameEn": "Xbox Wireless Controller - Starfield Limited Edition",
    "colorName": "群星宇航科技白 (Starfield Limited Edition)",
    "colorHex": "#e11d48",
    "textColor": "#ffffff",
    "year": 2023,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-starfield-controller.png",
    "dpad": "混合式 8 向圆盘方向键 (深黑)",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "微软近年口碑顶峰的重磅限量版手柄。全透明扳机键内嵌青铜震动马达、飞船驾驶舱仪表盘式科技丝印、群星彩色星座条带标与双色科技握把。"
  },
  {
    "id": "series-20th-anniversary",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "special",
    "seriesTypeName": "官方特别版",
    "name": "Xbox 无线控制器 - Xbox 20 周年特别版",
    "nameEn": "Xbox Wireless Controller - 20th Anniversary Special Edition",
    "colorName": "20 周年半透明黑与荧光绿核心",
    "colorHex": "#06b6d4",
    "textColor": "#ffffff",
    "year": 2021,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-20th-anniversary-controller.png",
    "dpad": "混合式 8 向圆盘方向键 (冰川白)",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "致敬初代 Xbox 诞生 20 周年的标志性特别版。半透明哑光黑外壳可窥见内部微观机械结构，经典初代荧光绿 X 导航键，连接主机可解锁专属纪念动态背景。"
  },
  {
    "id": "series-storm-breaker",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "special",
    "seriesTypeName": "官方特别版",
    "name": "Xbox 无线控制器 - 风暴蓝特别版",
    "nameEn": "Xbox Wireless Controller - Stormcloud Vapor Special Edition",
    "colorName": "风暴蓝 (Stormcloud Vapor Special Edition)",
    "colorHex": "#1e293b",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-storm-breaker-special-edition.png",
    "dpad": "混合式 8 向圆盘方向键 (深风暴灰)",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "狂暴雷霆云层撕裂的电光视觉。深空黑与风暴蓝闪电交织，霸气内敛，握持手感稳健扎实。"
  },
  {
    "id": "series-x25-anniversary",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "special",
    "seriesTypeName": "25周年典藏特别版",
    "name": "Xbox 无线控制器 - Xbox 25 周年特别版",
    "nameEn": "Xbox Wireless Controller - X25 Special Edition",
    "colorName": "经典半透翡翠绿 (Translucent 25th)",
    "colorHex": "#107c10",
    "textColor": "#ffffff",
    "year": 2026,
    "status": "upcoming",
    "statusLabel": "25周年预售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-25th-anniversary.png",
    "dpad": "高光金属翡翠绿混合十字键",
    "triggers": "暗夜半透明绿防滑扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（25 周年纪念标识独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥539 / $69.99",
    "description": "庆祝 Xbox 品牌诞生 25 周年特别版。传承初代 Halo 翡翠绿半透明经典材质，连入主机可自动解锁 25 周年独占动态背景。"
  },
  {
    "id": "series-doom-dark-ages",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 毁灭战士：黑暗时代限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - DOOM: The Dark Ages Limited Edition",
    "colorName": "中世纪地狱战甲 (DOOM Dark Ages)",
    "colorHex": "#7f1d1d",
    "textColor": "#ffffff",
    "year": 2025,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-doom-standard-limited-edition.png",
    "dpad": "做旧战损暗金金属 8 向十字键",
    "triggers": "血污战损金属涂层扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "id Software 史诗级新作《毁灭战士：黑暗时代》官方限定手柄。战甲盾牌徽记与地狱恶魔符文立体浮雕，极具压迫感。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "series-fallout-pip-boy",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 辐射避难所 Pip-Boy 限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - Fallout Pip-Boy Edition",
    "colorName": "废土哔哔小子工业绿 (Pip-Boy Olive)",
    "colorHex": "#3f6212",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-wireless-controller-fallout-pip-boy.png",
    "dpad": "哔哔小子复古仪表盘方向键",
    "triggers": "战前避难所防滑纹理扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "《辐射》全系列官方深度定制手柄。外壳以避难所科技经典草绿与避难所小子卡通贴纸组合，充满末日废土浪漫与复古未来主义情怀。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "series-cod-black-ops-6",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 使命召唤：黑色行动 6 限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - Call of Duty: Black Ops 6 Edition",
    "colorName": "特工隐秘行动 (Black Ops 6)",
    "colorHex": "#18181b",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-wireless-controller-call-of-duty.png",
    "dpad": "机密行动军工混合十字键",
    "triggers": "特战防滑纹理扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "Treyarch《使命召唤：黑色行动 6》官方联名手柄。融入海湾战争机密特工档案涂鸦与谍战暗号，带来身临其境的战地代入感。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "series-forza-5",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 -《极限竞速：地平线 5》限量版",
    "nameEn": "Xbox Wireless Controller - Forza Horizon 5 Limited Edition",
    "colorName": "地平线 5 狂飙黄透明款 (Forza Horizon 5)",
    "colorHex": "#e11d48",
    "textColor": "#ffffff",
    "year": 2021,
    "status": "upcoming",
    "statusLabel": "即将发售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-forza-horizon-5-controller.png",
    "dpad": "赛车打孔皮革触感圆盘方向键",
    "triggers": "赛道刹车卡钳触感扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "微软官方推出的高人气限量版控制器。采用亮黄色半透明定制外壳、首次引入的方向盘打孔赛车纹理握把与天蓝色底壳撞色，高度还原墨西哥开放世界的速度与狂欢。"
  },
  {
    "id": "series-gears-5",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 -《战争机器 5》凯特·迪亚兹限量版",
    "nameEn": "Xbox Wireless Controller - Gears 5 Kait Diaz Limited Edition",
    "colorName": "雪原战甲战损风 (Gears 5 Kait Diaz)",
    "colorHex": "#451a03",
    "textColor": "#ffffff",
    "year": 2019,
    "status": "upcoming",
    "statusLabel": "官方预告",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-gears-5-kait-controller.png",
    "dpad": "COG 齿轮金刚十字键",
    "triggers": "链锯枪机械防滑扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "微软官方发售的硬派限定手柄。以女主角凯特·迪亚兹防寒装甲为灵感，呈现极地冰雪战损风蚀刻质感，背部雕刻有猩红齿轮标记，配备橡胶防滑握把。"
  },
  {
    "id": "series-witcher-3",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 巫师 3 特别版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - The Witcher 3 Special Edition",
    "colorName": "白狼狼派徽章 (Witcher Wolf)",
    "colorHex": "#374151",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-witcher-standard.png",
    "dpad": "猎魔人银剑质感混合十字键",
    "triggers": "防滑纹理扳机键 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "CD Projekt RED《巫师 3：狂猎》官方 Design Lab 联名系列。利维亚的杰洛特标志性狼头勋章浮雕印刻，狩魔猎人专属装备。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "series-spongebob",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 海绵宝宝大电影限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - The SpongeBob Movie Limited Edition",
    "colorName": "比奇堡明黄色 (SpongeBob Yellow)",
    "colorHex": "#eab308",
    "textColor": "#111111",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-spongebob-movie-standard-xdl.png",
    "dpad": "蟹黄堡专属暗红圆盘十字键",
    "triggers": "波浪防滑纹理扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "微软派拉蒙官方合作《海绵宝宝大电影》限定版。将海绵宝宝经典笑容与比奇堡海洋元素带入掌心，充满童趣与快乐能量。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "series-ninja-gaiden-4",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 忍者龙剑传 4 官方设计版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - NINJA GAIDEN 4 Edition",
    "colorName": "隼流暗夜血刃 (Ninja Gaiden)",
    "colorHex": "#09090b",
    "textColor": "#ffffff",
    "year": 2025,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-ninja-gaiden-4-standard.png",
    "dpad": "龙剑流金十字键",
    "triggers": "忍杀微点防滑扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "Koei Tecmo Team Ninja 传奇动作硬派名作官方手柄。以隼龙战袍哑黑为主色调，点缀鲜血与刃芒金纹，极致凌厉。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "series-outerworlds-2",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 天外世界 2 官方设计版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - The Outer Worlds 2 Edition",
    "colorName": "太空殖民企业复古黄 (Halcyon Yellow)",
    "colorHex": "#d97706",
    "textColor": "#ffffff",
    "year": 2025,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-outerworlds-2-standard.png",
    "dpad": "星际飞船罗盘十字键",
    "triggers": "等离子枪微点防滑扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "黑曜石工作室《天外世界 2》官方设计版。充满 1950 年代美式复古未来主义海报美学与太空殖民垄断企业幽默讽刺标语。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "series-team-spirit",
    "generation": "series",
    "generationName": "Xbox Series X|S 世代",
    "seriesType": "limited",
    "seriesTypeName": "顶级联名典藏",
    "name": "Xbox 无线控制器 - 团队精神特别版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Wireless Controller - Team Spirit Limited Edition",
    "colorName": "战队电竞拼搏色 (Team Spirit)",
    "colorHex": "#2563eb",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-wireless-controller-team-spirit-limited-edition-with-xbox-design-lab.png",
    "dpad": "竞技高耐磨圆盘方向键",
    "triggers": "极速行程防滑扳机键",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "2 节 AA 电池或官方充电电池包（最长 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "有（实体独立 Share 键）",
    "weight": "287 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥599 / $79.99",
    "description": "微软专为全球电子竞技冠军打造的团队精神限定版，经由 Xbox Design Lab 深度定制，凝聚职业选手的荣耀与坚韧。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "elite-series-2-black",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "flagship",
    "seriesTypeName": "旗舰全配版",
    "name": "Xbox 精英无线控制器 2 代 - 旗舰黑",
    "nameEn": "Xbox Elite Wireless Controller Series 2 - Black",
    "colorName": "黑金旗舰全配 (Elite Black)",
    "colorHex": "#000000",
    "textColor": "#ffffff",
    "year": 2019,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2.png",
    "dpad": "可替换多面刻面十字键 + 标准经典十字键",
    "triggers": "三段式行程可调扳机锁 + 脉冲震动扳机",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置大容量可充电锂电池，单次续航长达 40 小时",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（通过按键映射任意背部拨片充当截屏）",
    "weight": "345 克（装配 4 拨片与多面十字键时）",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、macOS、iOS、Android",
    "msrp": "¥1,398 / $179.99",
    "description": "微软竞技游戏外设巅峰之作。全包覆防滑橡胶握把，摇杆张力阻尼 3 档无级可调，附带收纳硬包、4 枚不锈钢可拆背部拨片与磁吸充电底座。"
  },
  {
    "id": "elite-series-2-core-white",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "core",
    "seriesTypeName": "青春版核心款",
    "name": "Xbox 精英无线控制器 2 代 青春版（白色）",
    "nameEn": "Xbox Elite Wireless Controller Series 2 Core - White",
    "colorName": "纯白熊猫撞色 (Core White)",
    "colorHex": "#f8fafc",
    "textColor": "#111111",
    "year": 2022,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2-core.png",
    "dpad": "可替换十字键基座（标配标准十字键）",
    "triggers": "三段式行程可调扳机锁 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，最长 40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（自定义按键配置切换）",
    "weight": "330 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、macOS、iOS、Android",
    "msrp": "¥999 / $129.99",
    "description": "保留旗舰精英手柄的核心竞技性能（可调张力摇杆、短行程扳机锁与全包橡胶把手），去除后背拨片与便携包，以亲民门槛体验精英手感。"
  },
  {
    "id": "elite-series-2-core-red",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "core",
    "seriesTypeName": "青春版核心款",
    "name": "Xbox 精英无线控制器 2 代 青春版（红色）",
    "nameEn": "Xbox Elite Wireless Controller Series 2 Core - Red",
    "colorName": "烈焰红黑撞色 (Core Red)",
    "colorHex": "#dc2626",
    "textColor": "#ffffff",
    "year": 2023,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2-core-red.png",
    "dpad": "可替换十字键基座（标配哑光黑十字键）",
    "triggers": "三段式行程可调扳机锁 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，最长 40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（自定义按键配置切换）",
    "weight": "330 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、macOS、iOS、Android",
    "msrp": "¥1,099 / $139.99",
    "description": "炽烈激昂的深红主色面壳，与黑色全包覆环绕握把形成鲜明对比，展现极致电竞血统。"
  },
  {
    "id": "elite-series-2-core-blue",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "core",
    "seriesTypeName": "青春版核心款",
    "name": "Xbox 精英无线控制器 2 代 青春版（蓝色）",
    "nameEn": "Xbox Elite Wireless Controller Series 2 Core - Blue",
    "colorName": "蔚蓝深海撞色 (Core Blue)",
    "colorHex": "#2563eb",
    "textColor": "#ffffff",
    "year": 2023,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2-core-blue.png",
    "dpad": "可替换十字键基座（标配哑光黑十字键）",
    "triggers": "三段式行程可调扳机锁 + 脉冲震动",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，最长 40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（自定义按键配置切换）",
    "weight": "330 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、macOS、iOS、Android",
    "msrp": "¥1,099 / $139.99",
    "description": "深邃高饱和的电竞蓝涂装，与黑色环绕橡胶握把及全金属扳机键完美契合。"
  },
  {
    "id": "elite-series-2-doom",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "limited",
    "seriesTypeName": "精英联名限定款",
    "name": "Xbox 精英无线控制器 2 代 - 毁灭战士限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Elite Wireless Controller Series 2 - DOOM: The Dark Ages Edition",
    "colorName": "毁灭战甲暗金 (DOOM Elite)",
    "colorHex": "#78350f",
    "textColor": "#ffffff",
    "year": 2025,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-doom-elite-limited-edition.png",
    "dpad": "全金属做旧地狱浮雕十字键",
    "triggers": "三段式可调行程金属扳机锁",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（背部拨片映射）",
    "weight": "345 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11",
    "msrp": "¥1,699 / $199.99",
    "description": "Xbox Design Lab 与 id Software 联手打造的顶级精英限定版。盾牌纹章与中世纪战甲蚀刻，专为最挑剔的硬核屠魔战士定制。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "elite-series-2-fallout",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "limited",
    "seriesTypeName": "精英联名限定款",
    "name": "Xbox 精英无线控制器 2 代 - 辐射哔哔小子限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Elite Wireless Controller Series 2 - Fallout Pip-Boy Edition",
    "colorName": "避难所科技军工绿 (Pip-Boy Elite)",
    "colorHex": "#365314",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-fallout-pip-boy-elite-xdl.png",
    "dpad": "哔哔小子雷达刻度全金属十字键",
    "triggers": "三段式可调行程金属扳机锁",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（背部拨片映射）",
    "weight": "345 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11",
    "msrp": "¥1,699 / $199.99",
    "description": "融入废土避难所生锈金属包边与哔哔小子黄绿专属配色的顶级精英手柄。配备全套定制拨片与避难所小子专属收纳包。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "elite-series-2-cod",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "limited",
    "seriesTypeName": "精英联名限定款",
    "name": "Xbox 精英无线控制器 2 代 - 使命召唤：黑色行动 6 限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Elite Wireless Controller Series 2 - Call of Duty: Black Ops 6 Edition",
    "colorName": "绝密特战碳纤 (CoD Black Ops 6)",
    "colorHex": "#18181b",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2-call-of-duty.png",
    "dpad": "夜视镜战术准星刻度金属十字键",
    "triggers": "三段式可调行程金属扳机锁",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（背部拨片映射）",
    "weight": "345 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11",
    "msrp": "¥1,699 / $199.99",
    "description": "FPS 职业电竞选手的终极武器。暗夜灰与谍战机密档案融合，短行程扳机锁助你开镜击发抢占绝对先机。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "elite-series-2-witcher",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "limited",
    "seriesTypeName": "精英联名限定款",
    "name": "Xbox 精英无线控制器 2 代 - 巫师 3 限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Elite Wireless Controller Series 2 - The Witcher 3 Edition",
    "colorName": "银剑铭文暗夜灰 (Witcher Elite)",
    "colorHex": "#1f2937",
    "textColor": "#ffffff",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-witcher-elite.png",
    "dpad": "符文狼头金属十字键",
    "triggers": "三段式可调行程金属扳机锁",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（背部拨片映射）",
    "weight": "345 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11",
    "msrp": "¥1,699 / $199.99",
    "description": "猎魔人最高试炼之作。狼派法印立体铭刻在黑色橡胶握把之上，随附镌刻中世纪钢剑纹理的背部拨片。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "elite-series-2-ninja-gaiden",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "limited",
    "seriesTypeName": "精英联名限定款",
    "name": "Xbox 精英无线控制器 2 代 - 忍者龙剑传 4 限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Elite Wireless Controller Series 2 - NINJA GAIDEN 4 Edition",
    "colorName": "真龙剑黑金魂 (Ninja Gaiden Elite)",
    "colorHex": "#09090b",
    "textColor": "#ffffff",
    "year": 2025,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-ninja-gaiden-4-elite.png",
    "dpad": "八卦龙牙锻造金属十字键",
    "triggers": "三段式极速短行程金属扳机锁",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（背部拨片映射）",
    "weight": "345 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11",
    "msrp": "¥1,699 / $199.99",
    "description": "硬核动作动作天花板联名。极致短行程扳机锁配合背面自定义四拨片，完美执行饭纲落与绝啸热血连段。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "elite-series-2-outerworlds",
    "generation": "elite",
    "generationName": "Xbox 精英手柄世代",
    "seriesType": "limited",
    "seriesTypeName": "精英联名限定款",
    "name": "Xbox 精英无线控制器 2 代 - 天外世界 2 限定版 [🇺🇸 美国限定·国行未售]",
    "nameEn": "Xbox Elite Wireless Controller Series 2 - The Outer Worlds 2 Edition",
    "colorName": "企业至尊奢华金 (Board Golden)",
    "colorHex": "#b45309",
    "textColor": "#ffffff",
    "year": 2025,
    "status": "active",
    "statusLabel": "官方限定",
    "salesRegion": "us_only",
    "image": "./assets/products/xbox-outerworlds-2-elite.png",
    "dpad": "黄金时代电镀金属十字键",
    "triggers": "三段式可调行程金属扳机锁",
    "connectivity": "Xbox 无线协议 + 蓝牙低功耗 (BLE) + USB-C",
    "battery": "内置可充电锂电池，40 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（背部拨片映射）",
    "weight": "345 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11",
    "msrp": "¥1,699 / $199.99",
    "description": "翡翠鸟星系最高董事会专享顶级装备。融合复古电镀金色按键与企业宣传复古海报雕花。【发售区域说明】本款式为美国微软商店与海外地区独占发售，微软中国大陆官方未正式引进销售。"
  },
  {
    "id": "xbox-adaptive-controller",
    "generation": "adaptive",
    "generationName": "Xbox 包容无障碍系列",
    "seriesType": "adaptive",
    "seriesTypeName": "无障碍中枢",
    "name": "Xbox 无障碍自适应控制器",
    "nameEn": "Xbox Adaptive Controller",
    "colorName": "极简包容白 (Adaptive White)",
    "colorHex": "#ffffff",
    "textColor": "#111111",
    "year": 2018,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-adaptive-controller.png",
    "dpad": "超大直径平滑黑白圆盘十字键",
    "triggers": "通过外部 3.5mm 接口接入脚踏开关或吸管传感器",
    "connectivity": "Xbox 无线协议 + 蓝牙 + USB-C + 19 个 3.5mm 扩展孔",
    "battery": "内置可充电锂电池，最长 25 小时续航",
    "headphoneJack": "3.5mm 立体声耳机插孔",
    "shareBtn": "无（可通过按键映射指派）",
    "weight": "552 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11",
    "msrp": "¥799 / $99.99",
    "description": "微软包容性设计的里程碑。背板配备 19 个 3.5 毫米外部开关插孔、2 个 USB 端口与三脚架固定螺孔，让每一位玩家都能享受游戏乐趣。"
  },
  {
    "id": "xbox-adaptive-joystick",
    "generation": "adaptive",
    "generationName": "Xbox 包容无障碍系列",
    "seriesType": "adaptive",
    "seriesTypeName": "自适应摇杆",
    "name": "Xbox 自适应游戏摇杆",
    "nameEn": "Xbox Adaptive Joystick",
    "colorName": "无障碍纯白 (Adaptive White)",
    "colorHex": "#ffffff",
    "textColor": "#111111",
    "year": 2024,
    "status": "active",
    "statusLabel": "官方在售",
    "salesRegion": "cn_official",
    "image": "./assets/products/xbox-adaptive-joystick.png",
    "dpad": "摇杆推向输入 / 4 个可自定义表面按键",
    "triggers": "单手可及的人体工程学微动扳机",
    "connectivity": "USB-C 直连 Xbox 主机、PC 或 Adaptive Controller",
    "battery": "有线供电 / 极低输入延迟",
    "headphoneJack": "通过主控设备输出",
    "shareBtn": "可通过 Xbox Accessories 软件映射",
    "weight": "160 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Xbox 自适应控制器",
    "msrp": "¥249 / $29.99",
    "description": "微软专为活动能力受限玩家研发的有线单手摇杆配件。支持多角度旋转安装，摇杆帽可免费 3D 打印替换。"
  },
  {
    "id": "one-standard-black",
    "generation": "one",
    "generationName": "Xbox One 世代",
    "seriesType": "classic",
    "seriesTypeName": "初代标配",
    "name": "Xbox One 无线控制器 - 经典黑 (2013 初版)",
    "nameEn": "Xbox One Wireless Controller - Standard Black",
    "colorName": "经典曜石黑 (Matte Black)",
    "colorHex": "#1a1a1a",
    "textColor": "#ffffff",
    "year": 2013,
    "status": "discontinued",
    "statusLabel": "历史停产",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-one-controller-black.png",
    "dpad": "全金属微动 4 向经典十字键（清脆微动机械手感）",
    "triggers": "行业首创 2 个脉冲独立震动扳机 (Impulse Triggers)",
    "connectivity": "Xbox 专有无线协议（无蓝牙）+ Micro-USB",
    "battery": "2 节 AA 电池（续航约 30 小时）",
    "headphoneJack": "仅专有拓展音频端口（无 3.5mm，需外接耳机适配器）",
    "shareBtn": "无（通过连按两次 Xbox 键录屏）",
    "weight": "280 克",
    "compatibility": "Xbox One 全系列主机、Windows 7/8/10（需无线适配器）",
    "msrp": "¥399 / $59.99",
    "description": "Xbox One 首发划时代手柄。历时超 1 亿美元研发，带来超过 40 项工程改进，首次搭载革命性的脉冲震动扳机。"
  },
  {
    "id": "one-s-white",
    "generation": "one",
    "generationName": "Xbox One 世代",
    "seriesType": "classic",
    "seriesTypeName": "蓝牙升级版",
    "name": "Xbox One S 无线控制器 - 冰雪白 (2016 蓝牙版)",
    "nameEn": "Xbox One S Wireless Controller - Robot White",
    "colorName": "冰雪白一体成型 (One S White)",
    "colorHex": "#f1f5f9",
    "textColor": "#111111",
    "year": 2016,
    "status": "discontinued",
    "statusLabel": "历史停产",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-one-controller-white.png",
    "dpad": "4 向经典机械微动十字键",
    "triggers": "脉冲震动扳机键 (微点纹理防滑把手)",
    "connectivity": "内置蓝牙 4.0（PC/手机免接收器直连）+ Xbox 无线 + Micro-USB",
    "battery": "2 节 AA 电池（续航约 40 小时）",
    "headphoneJack": "3.5mm 立体声耳机接口 (CTIA 标准)",
    "shareBtn": "无",
    "weight": "280 克",
    "compatibility": "Xbox Series X|S、Xbox One、Windows 10/11、Android、iOS",
    "msrp": "¥429 / $59.99",
    "description": "Xbox One S 主机标配手柄。首次将正面顶盖与 Xbox 按键周边区域一体化流线注塑，首次内置蓝牙协议，支持 Windows 10/手机直连。"
  },
  {
    "id": "360-wireless-white",
    "generation": "360",
    "generationName": "Xbox 360 黄金世代",
    "seriesType": "classic",
    "seriesTypeName": "黄金时代标杆",
    "name": "Xbox 360 经典无线手柄 - 亮白 (2005 首发)",
    "nameEn": "Xbox 360 Wireless Controller - White",
    "colorName": "典雅乳白 (Arctic White)",
    "colorHex": "#e2e8f0",
    "textColor": "#111111",
    "year": 2005,
    "status": "discontinued",
    "statusLabel": "名人堂典藏",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-360-controller-white.png",
    "dpad": "一体式 8 向凸起十字键",
    "triggers": "人体工学弧形模拟线性扳机 (8 位精度)",
    "connectivity": "2.4 GHz 专有无线射频技术 (最远 9 米)",
    "battery": "背负式凸起可拆卸 AA 电池盒或可充电镍氢电池包",
    "headphoneJack": "2.5mm Xbox 语音单耳耳麦插口",
    "shareBtn": "无（Guide 环形四象限绿色导航光环）",
    "weight": "265 克（含电池）",
    "compatibility": "Xbox 360 主机全系列、Windows PC（需 2.4G 无线接收器）",
    "msrp": "$49.99",
    "description": "主机手柄工业设计史上难以逾越的丰碑。非对称双摇杆黄金布局、四色水晶字母按键与中央环形绿光导航键，统治 PC 游戏手柄十余年。"
  },
  {
    "id": "360-wireless-black",
    "generation": "360",
    "generationName": "Xbox 360 黄金世代",
    "seriesType": "classic",
    "seriesTypeName": "Elite 尊享版",
    "name": "Xbox 360 典雅黑手柄 (Elite 黑版)",
    "nameEn": "Xbox 360 Wireless Controller - Matte Black",
    "colorName": "沉稳纯黑 (Elite Matte Black)",
    "colorHex": "#1e293b",
    "textColor": "#ffffff",
    "year": 2007,
    "status": "discontinued",
    "statusLabel": "名人堂典藏",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-360-controller-black.png",
    "dpad": "一体式 8 向十字键",
    "triggers": "人体工学弧形模拟线性扳机",
    "connectivity": "2.4 GHz 专有无线射频",
    "battery": "黑色背负式 AA 电池盒",
    "headphoneJack": "2.5mm 语音插口",
    "shareBtn": "无",
    "weight": "265 克",
    "compatibility": "Xbox 360、Windows PC",
    "msrp": "$49.99",
    "description": "伴随 Xbox 360 Elite 黑色旗舰主机同步登场的全黑手柄。浑然一体的深邃纯黑哑光外壳，成为无数 PC 竞技玩家的挚爱标配。"
  },
  {
    "id": "360-emerald-green",
    "generation": "360",
    "generationName": "Xbox 360 黄金世代",
    "seriesType": "classic",
    "seriesTypeName": "特别限定色",
    "name": "Xbox 360 翡翠绿无线手柄",
    "nameEn": "Xbox 360 Wireless Controller - Emerald Green",
    "colorName": "透光翡翠绿 (Emerald Green)",
    "colorHex": "#15803d",
    "textColor": "#ffffff",
    "year": 2008,
    "status": "discontinued",
    "statusLabel": "限量收藏",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-360-controller-green.png",
    "dpad": "一体式 8 向十字键",
    "triggers": "人体工学弧形模拟线性扳机",
    "connectivity": "2.4 GHz 专有无线射频",
    "battery": "绿色背负式 AA 电池盒",
    "headphoneJack": "2.5mm 语音插口",
    "shareBtn": "无",
    "weight": "265 克",
    "compatibility": "Xbox 360、Windows PC",
    "msrp": "$59.99",
    "description": "Xbox 360 世代最经典的半透明限定手柄之一。通体透亮的翡翠绿外壳，致敬 Xbox 初代品牌的经典翡翠绿色系。"
  },
  {
    "id": "360-halo-odst",
    "generation": "360",
    "generationName": "Xbox 360 黄金世代",
    "seriesType": "classic",
    "seriesTypeName": "光环典藏版",
    "name": "Xbox 360 光环 3: ODST 限量版手柄",
    "nameEn": "Xbox 360 Wireless Controller - Halo 3: ODST Edition",
    "colorName": "地狱伞兵战术绿 (ODST Tactical Green)",
    "colorHex": "#3f6212",
    "textColor": "#ffffff",
    "year": 2009,
    "status": "discontinued",
    "statusLabel": "绝版典藏",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-360-controller-halo.png",
    "dpad": "一体式 8 向战术黑十字键",
    "triggers": "弧形线性扳机键",
    "connectivity": "2.4 GHz 专有无线射频",
    "battery": "军工黑 AA 电池盒",
    "headphoneJack": "2.5mm 语音插口",
    "shareBtn": "无",
    "weight": "265 克",
    "compatibility": "Xbox 360、Windows PC",
    "msrp": "$59.99",
    "description": "伴随 Bungie 传奇巨作《光环 3：地狱伞兵》发售的官方限量版手柄。手柄表面印刻 UNSC 军徽与 ODST 战术迷彩涂鸦。"
  },
  {
    "id": "original-the-duke",
    "generation": "original",
    "generationName": "初代 Xbox 开创纪元",
    "seriesType": "classic",
    "seriesTypeName": "历史开山鼻祖",
    "name": "初代 Xbox 控制器 - The Duke (2001)",
    "nameEn": "Original Xbox Controller - The Duke",
    "colorName": "初代巨兽黑 (Duke Black)",
    "colorHex": "#09090b",
    "textColor": "#ffffff",
    "year": 2001,
    "status": "discontinued",
    "statusLabel": "历史文物",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-controller-duke.png",
    "dpad": "大型隆起 8 向圆盘十字键",
    "triggers": "2 个深行程模拟线性扳机键",
    "connectivity": "专有防拉扯分段式有线连接线 (3 米长)",
    "battery": "主机有线供电（无需电池）",
    "headphoneJack": "双扩展插槽（用于插记忆卡或 Xbox Live 耳麦）",
    "shareBtn": "无（配备黑/白辅助按键与巨型凸起水晶 Xbox 徽章）",
    "weight": "385 克（体量巨大，双手饱满握持）",
    "compatibility": "初代 Xbox 主机",
    "msrp": "$39.99",
    "description": "Xbox 历史传奇“大胖”手柄 The Duke。中央嵌有一颗巨大的翡翠绿凸起 Xbox 水晶 Logo，按键巨大厚重，成为游戏硬件史上的独一无二经典图腾。"
  },
  {
    "id": "original-controller-s",
    "generation": "original",
    "generationName": "初代 Xbox 开创纪元",
    "seriesType": "classic",
    "seriesTypeName": "灵动轻量升级",
    "name": "初代 Xbox 控制器 - Controller S (2002)",
    "nameEn": "Original Xbox Controller - Controller S",
    "colorName": "纯黑修身款 (Matte Black S)",
    "colorHex": "#18181b",
    "textColor": "#ffffff",
    "year": 2002,
    "status": "discontinued",
    "statusLabel": "历史停产",
    "salesRegion": "legacy",
    "image": "./assets/products/xbox-controller-s.png",
    "dpad": "平滑优化 8 向十字键",
    "triggers": "2 个改良人体工学模拟线性扳机",
    "connectivity": "防拉扯分离式有线连接",
    "battery": "主机有线供电",
    "headphoneJack": "双记忆卡与耳麦扩展槽",
    "shareBtn": "无（黑白两键移至十字键下方）",
    "weight": "260 克",
    "compatibility": "初代 Xbox 主机",
    "msrp": "$39.99",
    "description": "针对亚洲玩家手型深度改良的紧凑型控制器。由于极佳的人体工程学握持反馈，微软于 2002 年将其扶正为初代 Xbox 全球标准标配手柄。"
  }
];

var XBOX_ACCESSORIES = [
  {
    "id": "xbox-wireless-headset",
    "name": "Xbox 无线耳机",
    "nameEn": "Xbox Wireless Headset",
    "category": "audio",
    "categoryName": "官方音频设备",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-wireless-headset.png",
    "price": "¥799 / $99.99",
    "details": {
      "driver": "40 毫米钕磁铁扬声单元",
      "spatialAudio": "支持 Dolby Atmos、DTS Headphone:X 与 Windows Sonic 空间音效",
      "connectivity": "Xbox 无线专有协议直接与主机配对（无需适配器）+ 蓝牙 4.2 双模并发",
      "battery": "内置锂电池，充满最长续航 15 小时；充电 30 分钟可提供约 4 小时续航",
      "mic": "双麦克风波束成形阵列，支持自动静音与语音隔离算法",
      "controls": "左右旋转式耳罩拨盘（左耳调节游戏/语音平衡，右耳调节总音量）",
      "weight": "312 克"
    },
    "description": "专为主机玩家定制的高性能无线游戏耳机。无需适配器即可与 Xbox 主机直连，并可同时连接手机蓝牙，接听电话无需中断游戏。"
  },
  {
    "id": "xbox-stereo-headset",
    "name": "Xbox 有线立体声耳机",
    "nameEn": "Xbox Stereo Headset",
    "category": "audio",
    "categoryName": "官方音频设备",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-stereo-headset.png",
    "price": "¥459 / $59.99",
    "details": {
      "driver": "40 毫米高质量钕磁铁驱动单元",
      "spatialAudio": "支持 Windows Sonic、Dolby Atmos 与 DTS Headphone:X 空间立体环绕声",
      "connectivity": "3.5 毫米音频插孔（即插即用，零延迟）",
      "controls": "右耳罩旋转拨盘直接调节音量，右耳罩背部设有麦克风一键静音滑块",
      "weight": "286 克轻量化佩戴设计",
      "features": "超柔软亲肤大耳罩，可伸缩可折叠全向麦克风"
    },
    "description": "高性价比高舒适度官方有线电竞耳麦。3.5mm 标准音频线直连手柄耳机孔，耳罩集成物理旋钮音量调节。"
  },
  {
    "id": "xbox-seagate-1tb",
    "name": "希捷存储扩展卡 - 1TB",
    "nameEn": "Seagate Storage Expansion Card for Xbox Series X|S - 1TB",
    "category": "storage",
    "categoryName": "官方存储扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-seagate-1tb-expansion-card.png",
    "price": "¥1,299 / $149.99",
    "details": {
      "capacity": "1TB 闪存扩展容量（实际可用约 920GB）",
      "interface": "定制 PCIe 4.0 x2 NVMe 专有直连接口",
      "speed": "2.4 GB/s 原始读写吞吐，4.8 GB/s 硬件解压吞吐",
      "architecture": "100% 完整支持 Xbox Velocity Architecture（速度与内置 SSD 完全一致）",
      "features": "完美支持次世代 Xbox Series 专属游戏直接安装与流畅运行，支持快速唤醒 (Quick Resume)"
    },
    "description": "微软与希捷联合研发的次世代主机专用高速闪存卡。无缝插入主机背部专属插槽，性能与内置存储完全无差。"
  },
  {
    "id": "xbox-seagate-2tb",
    "name": "希捷存储扩展卡 - 2TB",
    "nameEn": "Seagate Storage Expansion Card for Xbox Series X|S - 2TB",
    "category": "storage",
    "categoryName": "官方存储扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-seagate-2tb-expansion-card.png",
    "price": "¥2,399 / $279.99",
    "details": {
      "capacity": "2TB 超大容量极速闪存空间",
      "interface": "定制 PCIe 4.0 x2 NVMe 专属热插拔接口",
      "speed": "2.4 GB/s 原始吞吐，4.8 GB/s 硬件解压吞吐",
      "architecture": "完整支持 Xbox Velocity 架构，与内置 SSD 协同组成海量极速游戏库",
      "features": "可容纳数十款 3A 巨作（如极限竞速、战争机器、使命召唤）"
    },
    "description": "2TB 顶配扩展容量，为硬核主机玩家打造的海量游戏仓库。无需反复下载卸载，随时畅玩次世代庞大游戏库。"
  },
  {
    "id": "xbox-seagate-4tb",
    "name": "希捷存储扩展卡 - 4TB",
    "nameEn": "Seagate Storage Expansion Card for Xbox Series X|S - 4TB",
    "category": "storage",
    "categoryName": "官方存储扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-seagate-4tb-expansion-card.png",
    "price": "¥4,199 / $499.99",
    "details": {
      "capacity": "4TB 极限海量存储空间",
      "interface": "定制 PCIe 4.0 x2 专有直插通道",
      "speed": "2.4 GB/s 原始吞吐 / 4.8 GB/s 解压读写",
      "architecture": "完全契合 Xbox Velocity 架构，支持次世代专属强化游戏与快速唤醒",
      "features": "终极发烧友配置，彻底释放次世代主机游戏存储焦虑"
    },
    "description": "希捷专为 Xbox Series X|S 打造的 4TB 旗舰存储卡。满足骨灰级玩家对于数十款大型 3A 游戏常驻主机的使用需求。"
  },
  {
    "id": "xbox-wd-black-512gb",
    "name": "西数 WD_BLACK C50 扩展卡 - 512GB",
    "nameEn": "WD_BLACK C50 Storage Expansion Card for Xbox Series X|S - 512GB",
    "category": "storage",
    "categoryName": "官方存储扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-wd-black-c50-512gb-expansion-card-for-xbox-series-x-s.png",
    "price": "¥599 / $79.99",
    "details": {
      "capacity": "512GB 官方认证扩展容量",
      "interface": "Xbox 专有存储扩展槽 PCIe NVMe 接口",
      "speed": "符合 Xbox Velocity 架构高速读写吞吐标准",
      "architecture": "官方授权，支持 Series X|S 优化游戏直接运行与 Quick Resume",
      "features": "工业风军规散热条纹外壳，即插即用"
    },
    "description": "西部数据旗下黑盘（WD_BLACK）系列官方认证扩展卡。以极具竞争力的价格为 Xbox Series S/X 玩家提供即时扩容。"
  },
  {
    "id": "xbox-wd-black-1tb",
    "name": "西数 WD_BLACK C50 扩展卡 - 1TB",
    "nameEn": "WD_BLACK C50 Storage Expansion Card for Xbox Series X|S - 1TB",
    "category": "storage",
    "categoryName": "官方存储扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-wd-black-c50-1tb-expansion-card-for-xbox-series-x-s.png",
    "price": "¥1,099 / $149.99",
    "details": {
      "capacity": "1TB 官方认证高速扩展空间",
      "interface": "Xbox 专有存储扩展端口",
      "speed": "2.4 GB/s 原始吞吐，与内置 NVMe 性能协同一致",
      "architecture": "支持完整 Xbox Velocity Architecture",
      "features": "军规工业硬朗质感金属外壳，持久高效温控散热"
    },
    "description": "WD_BLACK C50 1TB 官方扩展卡。为玩家提供第二种高品质官方认证存储选择，无缝即插即用。"
  },
  {
    "id": "xbox-complete-component-pack",
    "name": "Xbox 精英手柄 2 代完整配件包",
    "nameEn": "Xbox Elite Wireless Controller Series 2 Complete Component Pack",
    "category": "accessories",
    "categoryName": "官方配件与扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-complete-component-pack.png",
    "price": "¥499 / $59.99",
    "details": {
      "features": "包含 1 个可替换多面刻面十字键、4 个不锈钢背部拨片（2 中 2 小）、4 个可替换摇杆（2 经典、1 高凸、1 宽圆顶）",
      "accessories": "附带专用磁吸充电底座、便携硬壳收纳包、摇杆阻尼调节扳手与 2.7 米编织 USB-C 编织线",
      "compatibility": "专为 Xbox 精英无线控制器 2 代 青春版（Core）升级为全配版量身打造"
    },
    "description": "微软官方推出的精英 2 代全套配件升级包。让拥有 Core 青春版手柄的玩家能够一站式配齐所有金属背部拨片、充电底座与收纳盒。"
  },
  {
    "id": "xbox-elite-carrying-case",
    "name": "Xbox 精英手柄 2 代收纳包与充电底座",
    "nameEn": "Xbox Elite Series 2 Carrying Case and Charging Pack",
    "category": "accessories",
    "categoryName": "官方配件与扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2-carrying-case-and-charging-pack.png",
    "price": "¥299 / $39.99",
    "details": {
      "features": "硬壳抗压便携收纳包，包内内置专属磁吸充电底座，支持收纳包闭合状态下外接 USB-C 进行透壳充电",
      "compatibility": "适用于所有 Xbox 精英无线控制器 2 代及 2 代青春版手柄"
    },
    "description": "官方出品的高品质便携保护硬包。包体内部精密模具完美嵌合手柄，磁吸充电座牢牢吸附，出行收纳防尘防跌落。"
  },
  {
    "id": "xbox-elite-paddle-pack",
    "name": "Xbox 精英手柄 2 代背部拨片包",
    "nameEn": "Xbox Elite Series 2 Paddle Pack",
    "category": "accessories",
    "categoryName": "官方配件与扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2-paddle-pack.png",
    "price": "¥149 / $19.99",
    "details": {
      "features": "4 枚精工不锈钢背部拨片（2 枚中型短拨片、2 枚迷你拨片），磁吸式免工具秒级卡入安装",
      "compatibility": "兼容 Xbox 精英手柄 2 代及 Core 青春版系列"
    },
    "description": "官方背部金属拨片替换装。为玩家在紧张竞技中提供四指无缝映射输入，大拇指无需离开右摇杆即可完成跳跃、换弹与瞄准。"
  },
  {
    "id": "xbox-elite-thumbstick-pack",
    "name": "Xbox 精英手柄 2 代摇杆与十字键包",
    "nameEn": "Xbox Elite Series 2 Thumbsticks and D-Pad Pack",
    "category": "accessories",
    "categoryName": "官方配件与扩展",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-elite-wireless-controller-series-2-thumbsticks-and-d-pad-pack.png",
    "price": "¥149 / $19.99",
    "details": {
      "features": "包含 4 枚高品质可替换摇杆帽（经典凹面、高凸面、宽大圆顶）+ 1 枚多面刻面十字键 + 1 枚调校扳手",
      "compatibility": "兼容 Xbox 精英手柄 2 代系列"
    },
    "description": "针对不同游戏类型（格斗、竞速、FPS 狙击）定制的摇杆与方向键模块，磁吸吸附稳固耐用。"
  },
  {
    "id": "xbox-rechargeable-battery",
    "name": "Xbox 可充电锂电池套件 (带 USB-C 数据线)",
    "nameEn": "Xbox Rechargeable Battery + USB-C Cable",
    "category": "power",
    "categoryName": "官方供电方案",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-rechargeable-battery.png",
    "price": "¥199 / $24.99",
    "details": {
      "batteryType": "官方定制 1400mAh 锂离子可充电电池包",
      "chargingTime": "约 4 小时即可完全充满",
      "batteryLife": "单次充满后游戏续航长达 30 至 40 小时",
      "cable": "随附 2.7 米 (9 英尺) 编织手感 USB-C 充电连接线",
      "features": "支持边玩边充（Play & Charge），待机状态亦可自动涓流补电，彻底告别一次性干电池",
      "compatibility": "兼容配备 USB-C 接口的所有 Xbox Series X|S 官方无线手柄"
    },
    "description": "微软专为 Xbox 无线控制器打造的官方锂电池供电方案。附带 2.7 米长线，边充边玩无拘无束。"
  },
  {
    "id": "xbox-wireless-adapter",
    "name": "Xbox 无线适配器 (Windows 10/11)",
    "nameEn": "Xbox Wireless Adapter for Windows 10/11",
    "category": "connectivity",
    "categoryName": "官方连接外设",
    "status": "active",
    "statusLabel": "官方在售",
    "image": "./assets/products/xbox-wireless-adapter.png",
    "price": "¥199 / $24.99",
    "details": {
      "port": "标准 USB 2.0 / USB 3.0 接口",
      "connectivity": "Xbox 专有双频无线射频通信技术（非普通蓝牙协议）",
      "latency": "接近零延迟的端到端超低传输响应，游戏级信号抗干扰",
      "capacity": "单适配器最多支持同时连接 8 个 Xbox 手柄 + 4 个聊天耳机或 2 个立体声耳机",
      "audioSupport": "完整支持手柄 3.5mm 耳机孔高品质立体声与麦克风语音无线传输",
      "dimensions": "体积较初代缩小 66%，仅如普通 U 盘般轻巧随身"
    },
    "description": "PC 玩家无线畅玩 Xbox 游戏的终极利器。采用微软专属专有无线协议，带来与主机完全一致的超低延迟与稳定无线音频传输。"
  }
];

// 挂载全局与模块导出
XBOX_LINEUP.controllers = XBOX_CONTROLLERS;
XBOX_LINEUP.accessories = XBOX_ACCESSORIES;

if (typeof window !== 'undefined') {
  window.XBOX_LINEUP = XBOX_LINEUP;
  window.XBOX_CONTROLLERS = XBOX_CONTROLLERS;
  window.XBOX_ACCESSORIES = XBOX_ACCESSORIES;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = XBOX_LINEUP;
  module.exports.controllers = XBOX_CONTROLLERS;
  module.exports.accessories = XBOX_ACCESSORIES;
}
