const assert = require('node:assert/strict');
const fs = require('fs');
const crypto = require('crypto');
global.SURFACE_DATA = require('../js/surface-data');
global.Catalog = require('../js/catalog');
global.ComparisonEngine = require('../js/comparison-engine');
global.ToolsEngine = require('../js/tools-engine');
const App = require('../js/app');
const t = ToolsEngine;
for(const value of ['1.22 千克','1.22 kg','1220 g','1220 克',{value:1.22,unit:'kg'}]) assert.equal(t.parseMass(value),1220);
for(const value of [null,'not_disclosed','not_applicable','1.2–1.4 kg','约 895 g / 900 g','895',{value:-1,unit:'g'}]) assert.equal(t.parseMass(value),null);
assert.equal(t.sumMass([1220,120,14,82]),1436);
assert.equal(t.sumMass([1220,null]),null);
assert.equal(t.sumMass([null,0]),null);
t.weightDeviceId='laptop-13-inch';t.weightWithKeyboard=false;t.weightWithPen=false;t.weightWithMouse=false;t.weightCharger='none';
assert.match(t.renderWeightCalculator(),/>1220 </);
t.weightWithPen=true;assert.match(t.renderWeightCalculator(),/待确认配置/);
assert.doesNotMatch(t.renderWeightCalculator(),/0\.68|真实办公续航估算/);
t.upgradeOldId='pro-7';t.upgradeNewId='pro-7';
assert.match(t.renderUpgradeAdvisor(),/同一设备，无升级差异/);
assert.doesNotMatch(t.renderUpgradeAdvisor(),/Slim Pen 2 纸感震动马达/);
const device = Catalog.getDevice('pro-7');const saved=device.specs.refreshRate;delete device.specs.refreshRate;
assert.doesNotMatch(t.renderUpgradeAdvisor(),/120Hz/);device.specs.refreshRate=saved;
const d = v => ({specs:{weightGrams:v}});
assert.equal(ComparisonEngine.checkFieldDiff([d('1.22 千克'),d('1220 g')],'weight'),false);
assert.equal(ComparisonEngine.checkFieldDiff([d(null),d('1220 g')],'weight'),true);
assert.equal(Catalog.npuScore('1 petaflop FP4'),null);
assert.equal(t.chipNpuScore({name:'RTX Spark',npuTops:1000,highlights:'1 petaflop FP4'}),null);
assert.equal(Catalog.npuScore({value:1000,scope:'platform',precision:'FP4',unit:'TOPS'}),null);
assert.equal(Catalog.npuScore({value:45,scope:'npu',precision:'INT8',unit:'TOPS'}),45);
assert.equal(t.getCompatStatus('flex-keyboard','no-such-device').status,'UNKNOWN');
const modal={innerHTML:'',style:{}};global.document={getElementById:()=>modal};
App.handleGlobalSearch('<img src=x onerror=alert(1)>');
assert.doesNotMatch(modal.innerHTML,/<img src=x/);assert.match(modal.innerHTML,/&lt;img/);
App.handleGlobalSearch('Pro 11');assert.match(modal.innerHTML,/pro-11-13/);
for(const budget of ['budget_entry','budget_mid','budget_high','budget_pro']) {
 t.onGuideFilterChange('budget',budget); assert.equal(t.guideBudget,budget);
 for(const dev of t.matchRecommendedDevices().matches) assert.ok(t.guidePassesFilters(dev));
}
const registry=JSON.parse(fs.readFileSync('docs/full-library-verification-registry.json'));
const fields=SURFACE_DATA.devices.flatMap(d=>Object.entries(d.specs).map(([field,value])=>({d,field,value})));
assert.equal(registry.entries.length,fields.length);
for(const {d,field,value} of fields){const e=registry.entries.find(e=>e.deviceId===d.id&&e.field===field);assert.ok(e);assert.equal(e.valueHash,crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex'));assert.equal(e.region,d.specs.salesRegion || (d.categoryId === 'xbox' ? 'UNKNOWN' : 'CN'));assert.equal(e.configuration,d.id);if(e.verdict==='VERIFIED'){assert.ok(e.reviewedAt&&e.sourceUrl)}}
assert.equal(require('../js/verification-status').resolve('pro-12-13-intel').status,'pending');
const evidence=require('../docs/evidence/ultra-business-cn-20261009.json');
assert.equal(evidence.region,'CN');assert.equal(evidence.consumerOrOtherRegionApplicable,false);assert.equal(evidence.values.batteryCapacityWh.minimum,89);assert.equal(evidence.values.npuInt8Tops,null);
assert.doesNotMatch(t.renderStorageGuide(),/100%|BYPASSNRO|10秒内无损/);
console.log('Review regression: mass arithmetic / unknowns / same-device / units / NPU scope / compatibility / XSS / search / budgets / all field hashes PASS');
const {correctUltraBusiness}=require('../scripts/verification/ultra-business-correction');
const consumer={id:'consumer-fixture',isCommercial:false,specs:{resolution:'unchanged'}};
const overseas={id:'overseas-fixture',isCommercial:true,specs:{officialDocUrl:'https://www.microsoft.com/en-us/surface',warranty:'unchanged'}};
const cn={id:'cn-fixture',isCommercial:true,specs:{officialDocUrl:evidence.sourceUrl,weight:'wrong'}};
const fixture={devices:[consumer,overseas,cn]};const corrected=correctUltraBusiness(fixture);
assert.deepEqual(corrected.dataset.devices[0],consumer);assert.deepEqual(corrected.dataset.devices[1],overseas);
assert.equal(corrected.dataset.devices[2].specs.resolution,'3270 × 2180');
assert.equal(corrected.dataset.devices[2].specs.weight,'2.0 kg');assert.equal(cn.specs.weight,'wrong');
assert.equal(corrected.dataset.devices[2].availability.shippingStarts,'2026-10-16');
assert.throws(()=>correctUltraBusiness({devices:[]}),/唯一/);
assert.throws(()=>correctUltraBusiness({devices:[cn,cn]}),/唯一/);
console.log('Ultra correction fixture PASS: exact China business source, consumer/other region preserved, no guessed IDs');
