const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const base=process.env.TEST_BASE || 'http://127.0.0.1:8765';
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const retry=await browser.newPage();
 let attempts=0;
 await retry.route('**/js/tools-engine.js*',r=>++attempts===1?r.abort():r.continue());
 await retry.goto(base+'/dist/site/#/tools/weight');
 await retry.getByRole('button',{name:'重新加载工具',exact:true}).click();
 await retry.locator('#tool-weight-calc-container').waitFor();
 assert.equal(attempts,2,'加载失败可重试，不缓存失败状态');
 await retry.close();
 const evidenceRetry=await browser.newPage();
 let evidenceAttempts=0;
 await evidenceRetry.route('**/js/field-evidence.*.js',r=>++evidenceAttempts===1?r.abort():r.continue());
 await evidenceRetry.goto(base+'/dist/site/#/business/laptop/laptop-ultra-biz');
 await evidenceRetry.getByRole('button',{name:'重新加载证据',exact:true}).click();
 await evidenceRetry.waitForFunction(()=>!Catalog.pendingEvidenceAsset());
 assert.equal(evidenceAttempts,2);await evidenceRetry.close();
 const evidenceRequests=[];page.on('request',r=>{if(r.url().includes('/js/field-evidence.'))evidenceRequests.push(r.url())});
 const toolsRequests=[];
 page.on('request',r=>{if(r.url().includes('/js/tools-engine.js'))toolsRequests.push(r.url())});
 await page.goto(base+'/dist/site/');
 assert.equal(await page.evaluate(()=>typeof ToolsEngine),'undefined');
 assert.equal(toolsRequests.length,0,'首页不请求工具引擎');
 assert.equal(evidenceRequests.length,0,'首页不请求字段证据分包');
 await page.evaluate(()=>App.navigate('#/tools/guide'));
 await page.locator('#tool-smart-guide-container').waitFor();
 assert.equal(toolsRequests.length,1,'首次工具导航只加载一次');
 assert.equal(evidenceRequests.length,1,'首次工具导航加载证据');
 assert.ok(await page.evaluate(()=>Catalog.evidenceFor(Catalog.getDevice('laptop-ultra-biz'),'resolution')));
 await page.evaluate(()=>App.navigate('#/tools/weight'));
 await page.locator('#tool-weight-calc-container').waitFor();
 assert.equal(toolsRequests.length,1,'其他工具复用已加载引擎');
 await page.goto(base+'/dist/site/#/tools/guide');
 await page.getByRole('button',{name:'入门便携',exact:false}).click();
 assert.equal(await page.evaluate(()=>ToolsEngine.guideBudget),'budget_entry');
 assert.match(await page.locator('#tool-smart-guide-container').innerText(),/符合条件 0 款/);
 await page.getByRole('button',{name:'主流进阶',exact:false}).click();
 assert.equal(await page.evaluate(()=>ToolsEngine.guideBudget),'budget_mid');
 assert.match(await page.locator('#tool-smart-guide-container').innerText(),/未核验的历史价格/);
 await page.getByRole('button',{name:'全部预算',exact:true}).click();
 assert.ok(await page.locator('.guide-card').count()>0);
 await page.locator('#global-search-input').focus();
 await page.evaluate(()=>App.handleGlobalSearch('Pro 11'));
 await page.keyboard.press('Escape');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'global-search-input');
 await page.evaluate(()=>App.handleGlobalSearch('Pro 11'));
 assert.equal(await page.getByRole('dialog').count(),1);
 await page.locator('#dialog-search-input').focus();
 await page.keyboard.press('Tab');
 assert.ok(await page.evaluate(()=>document.activeElement.closest('[role=dialog]') !== null));
 assert.ok(await page.locator('.search-result-item').count()>0);
 await page.locator('.search-result-item').first().focus();await page.keyboard.press('Enter');
 assert.match(page.url(),/pro-11/);
 await page.evaluate(()=>App.handleGlobalSearch('<img src=x onerror="window.pwned=true">'));
 assert.equal(await page.evaluate(()=>window.pwned),undefined);
 assert.equal(await page.locator('#search-results-modal img').count(),0);
 await page.evaluate(()=>App.closeSearchModal());
 await page.goto(base+'/dist/site/#/tools/weight');
 await page.evaluate(()=>{ToolsEngine.weightDeviceId='laptop-13-inch';ToolsEngine.weightWithKeyboard=false;ToolsEngine.weightWithPen=false;ToolsEngine.weightWithMouse=false;ToolsEngine.weightCharger='none';ToolsEngine.onWeightOptionChange('device','laptop-13-inch')});
 await page.locator('#tool-weight-calc-container').waitFor();
 assert.match(await page.locator('.weight-big-num').innerText(),/待确认配置/);
 await page.evaluate(()=>ToolsEngine.onWeightOptionChange('device','laptop-13-inch-biz'));
 assert.match(await page.locator('.weight-big-num').innerText(),/1220/);
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth), 'mobile must not overflow horizontally');
 await page.screenshot({path:'/tmp/surface-mobile-weight.png',fullPage:true});
 await page.goto(base+'/dist/site/#/audit');
 await page.evaluate(()=>{App.auditFilter='all';App.renderAuditView(document.getElementById('hub-main-content'))});
 for(const name of ['Surface Pro 初代', 'Surface Pro 2']) {
  const row=page.locator('tr').filter({hasText:name});assert.ok(await row.count()>0);assert.match(await row.first().innerText(),/16:9/);
 }
 const xbox=page.locator('tr').filter({hasText:'Xbox Series X 1TB（带光驱）'});assert.ok(await xbox.count()>0);assert.doesNotMatch(await xbox.first().innerText(),/3:2/);
 await page.goto(base+'/dist/site/#/business/laptop/laptop-ultra-biz');
 const bizText=await page.locator('#hub-main-content').innerText();
 assert.match(bizText,/3270/);assert.match(bizText,/92 Wh/);assert.match(bizText,/17.99/);assert.match(bizText,/3 年/);
 assert.doesNotMatch(bizText,/1000 TOPS|3nm|8 \/ 10|27,588/);
 await page.goto(base+'/dist/site/#/consumer/laptop/laptop-ultra');
 const consumerText=await page.locator('#hub-main-content').innerText();
 assert.match(consumerText,/尚未核验/);assert.match(consumerText,/不代表当前配置已确认/);assert.match(await page.locator('.utility-meta-list').innerText(),/历史记录日期\n待核验/);assert.doesNotMatch(consumerText,/已验证|官方未披露/);assert.doesNotMatch(consumerText,/3120|3270|90 Wh|92 Wh|1000 TOPS|21,988/);
 await page.goto(base+'/dist/site/products/laptop-ultra/');
 assert.doesNotMatch(await page.locator('main').innerText(),/3120|3270|90 Wh|92 Wh|1000 TOPS|21,988/);
 await page.goto(base+'/dist/site/products/pro-1/');
 assert.match(await page.locator('main').innerText(),/16:9/);
 assert.match(await page.locator('link[rel=canonical]').getAttribute('href'),/products\/pro-1\//);
 for(const file of ['robots.txt','sitemap.xml','build-info.json']){const r=await page.request.get(base+'/dist/site/'+file);assert.equal(r.status(),200);assert.doesNotMatch(await r.text(),/<!doctype html>/i)}
 await page.goto(base+'/dist/site/#/surface/pro/pro-1');
 assert.match(await page.locator('#hub-main-content').innerText(),/图片待核验，暂不展示/);
 assert.equal(await page.locator('#hub-main-content img[src*="surface-pro-1-hero"]').count(),0);
 await page.goto(base+'/dist/site/#/business/pro/pro-12-13-snap');
 assert.match(await page.locator('#hub-main-content').innerText(),/LCD \/ OLED/);
 assert.match(await page.locator('#hub-main-content').innerText(),/来源冲突/);
 await page.goto(base+'/dist/site/#/consumer/duo/duo-2');
 await page.waitForFunction(() => document.querySelector('#hub-main-content')?.innerText.includes('Surface Duo 2'));
 assert.match(await page.locator('#hub-main-content').innerText(),/图片待核验，暂不展示/);
 assert.equal(await page.locator('#hub-main-content img[src*="surface-duo-2-"]').count(),0);
 await page.goto(base+'/dist/site/#/consumer/laptop/laptop-ultra');
 await page.waitForFunction(() => document.querySelector('#hub-main-content')?.innerText.includes('独立产品级来源'));
 assert.match(await page.locator('#hub-main-content').innerText(),/不能确认中国消费者 SKU/);
 assert.equal(await page.locator('a[href="https://www.microsoft.com/en-us/surface/devices/surface-laptop-ultra"]').count(),1);
 await page.goto(base+'/dist/site/#/surface/pro/pro-7');
 await page.getByRole('button',{name:'报告参数问题',exact:true}).click();
 const correction=page.locator('dialog.correction-dialog');
 await correction.locator('select').selectOption('resolution');
 await correction.locator('input[name=source]').fill('https://support.microsoft.com/test');
 await correction.locator('textarea[name=note]').fill('<img src=x onerror="window.pwned=true"> 需要核对配置');
 await correction.getByRole('button',{name:'生成纠错草稿'}).click();
 assert.match(await correction.locator('.correction-output').inputValue(),/USER_DRAFT_NOT_VERIFIED/);
 assert.equal(await page.evaluate(()=>window.pwned),undefined);
 assert.equal(await correction.locator('img').count(),0);
 await page.keyboard.press('Escape');
 await correction.waitFor({state:'detached'});
 assert.equal(await correction.count(),0);
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'报告参数问题');
 assert.match(await page.locator('#hub-main-content').innerText(),/海外\/全球来源，非国行认证/);
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Browser PASS: desktop/mobile, real budget clicks, search keyboard + XSS, weight arithmetic, static detail/canonical/robots/sitemap/build metadata; no page errors');
})().catch(e=>{console.error(e);process.exit(1)});
