#!/usr/bin/env python3
"""Build delivery images from the master files in assets/.

Masters stay where they are. The site asks the browser for one AVIF or WebP
at the width of the real layout slot, not the original 1600px PNG.

Slots (CSS pixels, then 2x/3x):
  icon / audit / guide  -> 320
  card / comparison     -> 640
  detail hero           -> 1280

Images already smaller than a slot are not enlarged.
"""

import json
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ASSET_DIRS = ("assets/products", "assets/accessories")
OUT_ROOT = os.path.join(ROOT, "assets", "delivery")
MANIFEST_JS = os.path.join(ROOT, "js", "image-delivery.js")
CAPS = (320, 640, 1280)
# Product cutouts keep an alpha channel. 60 / 85 sit at the careful end of
# the AVIF 45-65 and WebP 75-85 ranges after checking a tablet, a laptop
# and a portrait accessory.
AVIF_QUALITY = 60
WEBP_QUALITY = 85


def chosen_widths(src_w):
    widths = [w for w in CAPS if w <= src_w]
    if not widths:
        return [src_w]
    if widths[-1] < src_w and src_w < CAPS[-1] and src_w - widths[-1] > 40:
        widths.append(src_w)
    return widths


def open_image(path):
    im = Image.open(path)
    im.load()
    has_alpha = im.mode in ("RGBA", "LA") or (im.mode == "P" and "transparency" in im.info)
    if has_alpha:
        return im.convert("RGBA"), True
    return im.convert("RGB"), False


def save_variant(im, width, dest_webp, dest_avif):
    nw = width
    nh = max(1, round(im.height * nw / im.width))
    out = im if im.width == nw else im.resize((nw, nh), Image.Resampling.LANCZOS)
    os.makedirs(os.path.dirname(dest_webp), exist_ok=True)
    os.makedirs(os.path.dirname(dest_avif), exist_ok=True)
    webp_kwargs = {"format": "WEBP", "quality": WEBP_QUALITY, "method": 6}
    if out.mode == "RGBA":
        webp_kwargs["alpha_quality"] = 100
    out.save(dest_webp, **webp_kwargs)
    out.save(dest_avif, format="AVIF", quality=AVIF_QUALITY, speed=6)
    # A transparent corner must stay transparent. Flattening paints a black or white box.
    if out.mode == "RGBA":
        for check in (dest_webp, dest_avif):
            probe = Image.open(check)
            if probe.mode != "RGBA":
                raise RuntimeError("alpha lost: " + check)


def main():
    table = {}
    masters = []
    for rel_dir in ASSET_DIRS:
        folder = os.path.join(ROOT, rel_dir)
        if not os.path.isdir(folder):
            continue
        for name in sorted(os.listdir(folder)):
            if not name.lower().endswith((".png", ".jpg", ".jpeg")):
                continue
            masters.append(os.path.join(folder, name))

    for index, src in enumerate(masters, 1):
        name = os.path.basename(src)
        stem = os.path.splitext(name)[0]
        im, _alpha = open_image(src)
        widths = chosen_widths(im.width)
        made = []
        for width in widths:
            webp = os.path.join(OUT_ROOT, "webp", "w%d" % width, stem + ".webp")
            avif = os.path.join(OUT_ROOT, "avif", "w%d" % width, stem + ".avif")
            fresh = (
                os.path.isfile(webp)
                and os.path.isfile(avif)
                and os.path.getsize(webp) > 0
                and os.path.getsize(avif) > 0
                and os.path.getmtime(webp) >= os.path.getmtime(src)
                and os.path.getmtime(avif) >= os.path.getmtime(src)
            )
            if not fresh:
                save_variant(im, width, webp, avif)
            made.append(width)
        table[name] = made
        print("%d/%d %s -> %s" % (index, len(masters), name, made))

    body = json.dumps(table, ensure_ascii=False, indent=2)
    js = (
        "/* Generated by scripts/deploy/optimize-images.py. Do not edit. */\n"
        "var IMAGE_DELIVERY = %s;\n"
        "if (typeof module !== 'undefined' && module.exports) module.exports = IMAGE_DELIVERY;\n"
        % body
    )
    with open(MANIFEST_JS, "w", encoding="utf-8") as handle:
        handle.write(js)
    print("manifest %d images" % len(table))


if __name__ == "__main__":
    main()
